In [1]:
# run this to shorten the data import from the files
path_data = '/home/nero/Documents/Estudos/DataCamp/Python/courses/Introduction_to_Deep_Learning_with_PyTorch/datasets/'

In [2]:
# exercise 01

"""
Using the TensorDataset class

In practice, loading your data into a PyTorch dataset will be one of the first steps you take in order to create and train a neural network with PyTorch.

The TensorDataset class is very helpful when your dataset can be loaded directly as a NumPy array. Recall that TensorDataset() can take one or more NumPy arrays as input.

In this exercise, you'll practice creating a PyTorch dataset using the TensorDataset class.

torch and numpy have already been imported for you, along with the TensorDataset class.
"""

# Instructions

"""

    Convert the NumPy arrays provided to PyTorch tensors.
    Create a TensorDataset using the torch_features and the torch_target tensors provided (in this order).
    Return the last element of the dataset.

"""

# solution

import numpy as np
import torch
from torch.utils.data import TensorDataset

np_features = np.array(np.random.rand(12, 8))
np_target = np.array(np.random.rand(12, 1))

# Convert arrays to PyTorch tensors
torch_features = torch.tensor(np_features)
torch_target = torch.tensor(np_target)

# Create a TensorDataset from two tensors
dataset = TensorDataset(torch_features, torch_target)

# Return the last element of this dataset
print(dataset[-1])

#----------------------------------#

# Conclusion

"""
TensorDataset is great to use when your dataset can be loaded from NumPy arrays (or converted to NumPy arrays). However, sometimes you need to code a custom dataset class. Let's do this next.
"""

(tensor([0.3983, 0.9102, 0.2561, 0.8858, 0.7375, 0.2554, 0.8681, 0.7920],
       dtype=torch.float64), tensor([0.9677], dtype=torch.float64))


"\nTensorDataset is great to use when your dataset can be loaded from NumPy arrays (or converted to NumPy arrays). However, sometimes you need to code a custom dataset class. Let's do this next.\n"

In [3]:
import pandas as pd

dataframe = pd.read_csv(path_data + 'water_potability.csv')

from torch.utils.data import DataLoader
import torch.nn as nn
import torch

In [4]:
dataframe.head()

ph  Hardness    Solids  Chloramines   Sulfate  Conductivity  \
0  0.587349  0.577747  0.386298     0.568199  0.647347      0.292985   
1  0.643654  0.441300  0.314381     0.439304  0.514545      0.356685   
2  0.388934  0.470876  0.506122     0.524364  0.561537      0.142913   
3  0.725820  0.715942  0.506141     0.521683  0.751819      0.148683   
4  0.610517  0.532588  0.237701     0.270288  0.495155      0.494792   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0        0.654522         0.795029   0.630115           0  
1        0.377248         0.202914   0.520358           0  
2        0.249922         0.401487   0.219973           0  
3        0.467200         0.658678   0.242428           0  
4        0.409721         0.469762   0.585049           0

In [5]:
# exercise 02

"""
From data loading to running a forward pass

In this exercise, you'll create a PyTorch DataLoader from a pandas DataFrame and call a model on this dataset. Specifically, you'll run a forward pass on a neural network. You'll continue working with fully connected neural networks, as you have done so far.

You'll begin by subsetting a loaded DataFrame called dataframe, converting features and targets NumPy arrays, and converting to PyTorch tensors in order to create a PyTorch dataset.

This dataset can be loaded into a PyTorch DataLoader, batched, shuffled, and used to run a forward pass on a custom fully connected neural network.

NumPy as np, pandas as pd, torch, TensorDataset(), and DataLoader() have been imported for you.
"""

# Instructions

"""

    Extract the features (ph, Sulfate, Conductivity, Organic_carbon) and target (Potability) values and load them into the appropriate tensors to represent features and targets.
    Use both tensors to create a PyTorch dataset using the dataset class that's quickest to use when tensors don't require any additional preprocessing.

---

    Create a PyTorch DataLoader from the created TensorDataset; this DataLoader should use a batch_size of two and shuffle the dataset.
---

    Implement a small, fully connected neural network using exactly two linear layers and the nn.Sequential() API, where the final output size is 1.

"""

# solution

# Load the different columns into two PyTorch tensors
features = torch.tensor(np.array(
  dataframe[['ph', 'Sulfate', 'Conductivity', 'Organic_carbon']])).float()
target = torch.tensor(np.array(
  dataframe['Potability'])).float()

# Create a dataset from the two generated tensors
dataset = TensorDataset(features, target)

# Create a dataloader using the above dataset
dataloader = DataLoader(dataset, shuffle=True, batch_size=2)
x, y = next(iter(dataloader))

# Create a model using the nn.Sequential API
model = nn.Sequential(
  nn.Linear(4,2),
  nn.Linear(2,1)
)
output = model(features)
print(output)

#----------------------------------#

# Conclusion

"""
Whether you work with tabular, image, or text data, this pipeline will remain the same but use other PyTorch dataset classes.
"""

tensor([[0.2107],
        [0.1997],
        [0.2487],
        ...,
        [0.1743],
        [0.1993],
        [0.1617]], grad_fn=<AddmmBackward0>)


'\nWhether you work with tabular, image, or text data, this pipeline will remain the same but use other PyTorch dataset classes.\n'

In [16]:
validationloader = dataloader
criterion = torch.nn.CrossEntropyLoss()

In [ ]:
# exercise 03

"""
Writing the evaluation loop

In this exercise, you will practice writing the evaluation loop. Recall that the evaluation loop is similar to the training loop, except that you will not perform the gradient calculation and the optimizer step.

The model has already been defined for you, along with the object validationloader, which is a dataset.
"""

# Instructions

"""

    Set the model to evaluation mode.
    Sum the current batch loss to the validation_loss variable.
---

    Calculate the mean loss value for the epoch.
    Set the model back to training mode.

"""

# solution

# Set the model to evaluation mode
model.eval()
validation_loss = 0.0

with torch.no_grad():
  
  for data in validationloader:
    
      outputs = model(data[0])
      loss = criterion(outputs, data[1])
      
      # Sum the current loss to the validation_loss variable
      validation_loss += loss.item()
      
# Calculate the mean loss value
validation_loss_epoch = validation_loss / len(validationloader)
print(validation_loss_epoch)

# Set the model back to training mode
model.train()

#----------------------------------#

# Conclusion

"""
Congratulations! Now you can add this validation loop after each training loop. Looking at ground truths, model predictions, and losses together is a great way to visualize if your model is learning!
"""

In [3]:
# exercise 04

"""
Calculating accuracy using torchmetrics

In addition to the losses, you should also be keeping track of the accuracy during training. By doing so, you will be able to select the epoch when the model performed the best.

In this exercise, you will practice using the torchmetrics package to calculate the accuracy. You will be using a sample of the facemask dataset. This dataset contains three different classes. The plot_errors function will display samples where the model predictions do not match the ground truth. Performing such error analysis will help you understand your model failure modes.

The torchmetrics package is already imported. The model outputs are the probabilities returned by a softmax as the last step of the model. The labels tensor contains the labels as one-hot encoded vectors.
"""

# Instructions

"""

    Create an accuracy metric for a "multiclass" problem with three classes.
    Calculate the accuracy for each batch of the dataloader.
---

    Calculate accuracy for the epoch.
    Reset the metric for the next epoch.

"""

# solution

# Create accuracy metric using torch metrics
metric = torchmetrics.Accuracy(task="multiclass", num_classes=3)
for data in dataloader:
    features, labels = data
    outputs = model(features)
    
    # Calculate accuracy over the batch
    acc = metric(outputs.softmax(dim=-1), labels.argmax(dim=-1))
    
# Calculate accuracy over the whole epoch
acc = metric.compute()

# Reset the metric for the next epoch 
metric.reset()
plot_errors(model, dataloader)

#----------------------------------#

# Conclusion

"""
The accuracy is a great metric for classification problems. Calculating the class-wise accuracy gives a better understanding of your model performances. Moreover, by looking at your model misclassification, you can find trends in the errors and better understand when your model fails.
"""

'\n\n'

In [23]:
# exercise 05

"""
Experimenting with dropout

The dropout layer randomly zeroes out elements of the input tensor. Doing so helps fight overfitting. In this exercise, you'll create a small neural network with at least two linear layers, two dropout layers, and two activation functions.

The torch.nn package has already been imported as nn. An input_tensor of dimensions 1X3072 has been created for you.
"""

# Instructions

"""

    Create a small neural network with one linear layer, one ReLU function, and one dropout layer, in that order.
    The model should take input_tensor as input and return an output of size 16.
---
    Using the same neural network, set the probability of zeroing out elements in the dropout layer to 0.8.

"""

# solution
input_tensor = torch.randn(1, 3072)

# Create a small neural network
model = nn.Sequential(
    nn.Linear(3072,16),
    nn.ReLU(),
    nn.Dropout(p=0.5)
)
display(model(input_tensor))

#----------------------------------#

# Using the same model, set the dropout probability to 0.8
model = nn.Sequential(
    nn.Linear(3072,16),
    nn.ReLU(),
    nn.Dropout(p=0.8)
)
display(model(input_tensor))

#----------------------------------#

# Conclusion

"""
Adding dropout layers is a parameter-free way to fight overfitting.
"""

tensor([[2.1103, 0.0000, 0.0000, 0.6276, 2.4426, 0.9137, 0.4977, 1.0354, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],
       grad_fn=<MulBackward0>)

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.6906, 0.0000,
         0.0000, 1.4975, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],
       grad_fn=<MulBackward0>)

'\nAdding dropout layers is a parameter-free way to fight overfitting.\n'

In [24]:
# exercise 06

"""
Implementing random search

Hyperparameter search is a computationally costly approach to experiment with different hyperparameter values. However, it can lead to performance improvements. In this exercise, you will implement a random search algorithm.

You will randomly sample 10 values of the learning rate and momentum from the uniform distribution. To do so, you will use the np.random.uniform() function.

The numpy package has already been imported as np.
"""

# Instructions

"""

    Randomly sample a learning rate factor such that the learning rate is bounded between 0.01 and 0.0001.
    Randomly sample a momentum between 0.85 and 0.99.

"""

# solution

values = []
for idx in range(10):
    # Randomly sample a learning rate factor between 0.01 and 0.0001
    factor = np.random.uniform(2,4)
    lr = 10 ** -factor
    
    # Randomly select a momentum between 0.85 and 0.99
    momentum = np.random.uniform(0.85,0.99)
    
    values.append((lr, momentum))

#----------------------------------#

# Conclusion

"""
Random search is a great way to fine-tune your hyperparameters. Upper and lower bounds should be carefully chosen to not waste computational power.
"""

'\nRandom search is a great way to fine-tune your hyperparameters. Upper and lower bounds should be carefully chosen to not waste computational power.\n'