In [2]:
# run this to shorten the data import from the files
path_data = '/home/nero/Documents/Estudos/DataCamp/Python/courses/Introduction_to_Deep_Learning_with_PyTorch/datasets/'
import pandas as pd
import pickle

In [4]:
# exercise 01

"""
Creating tensors and accessing attributes

Tensors are the primary data structure in PyTorch and will be the building blocks for our deep learning models. They share many similarities with NumPy arrays but have some unique attributes too.

In this exercise, you'll practice creating a tensor from a Python list and displaying some of its attributes.
"""

# Instructions

"""

    Begin by importing PyTorch.
    Create a tensor from the Python list list_a.
---

    Display the tensor device.
    Display the tensor data type.

"""

# solution

# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)

# Display the tensor device
print(tensor_a.device)

# Display the tensor data type
print(tensor_a.dtype)

#----------------------------------#

# Conclusion

"""
Accessing the different attributes of a tensor is critical for debugging, as many errors are related to operations on incompatible devices or data types.
"""

cpu
torch.int64


'\nAccessing the different attributes of a tensor is critical for debugging, as many errors are related to operations on incompatible devices or data types.\n'

In [5]:
import numpy as np

array_a = np.array([[1,1,1],[2,3,4],[4,5,6]])
array_b = np.array([[7,5,4],[2,2,8],[6,3,8]])

In [6]:
# exercise 02

"""
Creating tensors from NumPy arrays

Tensors are the fundamental data structure of PyTorch. You can create complex deep learning algorithms by learning how to manipulate them.

The torch package has been imported, and two NumPy arrays have been created, named array_a and array_b. Both arrays have the same dimensions.
"""

# Instructions

"""

    Create two tensors, tensor_a and tensor_b, from the NumPy arrays array_a and array_b, respectively.
    Subtract tensor_b from tensor_a.
    Perform an element-wise multiplication of tensor_a and tensor_b.
    Add the resulting tensors from the two previous steps together.

"""

# solution

# Create two tensors from the arrays
tensor_a = torch.tensor(array_a)
tensor_b = torch.tensor(array_b)

# Subtract tensor_b from tensor_a 
tensor_c = tensor_a - tensor_b

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b

# Add tensor_c with tensor_d
tensor_e = tensor_c + tensor_d
print(tensor_e) 

#----------------------------------#

# Conclusion

"""
Congratulations! Such tensor operations are used in modern deep learning architectures and mastering them is the first step on your journey to PyTorch mastery!
"""

tensor([[ 1,  1,  1],
        [ 4,  7, 28],
        [22, 17, 46]])


'\nCongratulations! Such tensor operations are used in modern deep learning architectures and mastering them is the first step on your journey to PyTorch mastery!\n'

In [7]:
# exercise 03

"""
Your first neural network

In this exercise, you will implement a small neural network containing two linear layers. The first layer takes an eight-dimensional input, and the last layer outputs a one-dimensional tensor.

The torch package and the torch.nn package have already been imported for you.
"""

# Instructions

"""
Create a neural network of linear layers that takes a tensor of dimensions 1 * 8  as input and outputs a tensor of dimensions 1 * 1
.
Use any output dimension for the first layer you want.
"""

# solution

import torch
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(nn.Linear(8,1),
nn.Linear(1,1)
                     )

output = model(input_tensor)
print(output)

#----------------------------------#

# Conclusion

"""
Good job on creating your first neural network! In practice, you'll find that modern neural networks can contain hundreds of layers and millions of parameters. Recall that the model output is not meaningful until the model is trained, i.e. until the weights and biases of each layer can meaningfully be used to produce output.
"""

tensor([[2.7354]], grad_fn=<AddmmBackward0>)


"\nGood job on creating your first neural network! In practice, you'll find that modern neural networks can contain hundreds of layers and millions of parameters. Recall that the model output is not meaningful until the model is trained, i.e. until the weights and biases of each layer can meaningfully be used to produce output.\n"

In [8]:
# exercise 04

"""
Using the sigmoid and softmax functions

The sigmoid and softmax functions are two of the most popular activation functions in deep learning. They are both usually used as the last step of a neural network. Sigmoid functions are used for binary classification problems, whereas softmax functions are often used for multi-class classification problems. This exercise will familiarize you with creating and using both functions.

Let's say that you have a neural network that returned the values contained in the score tensor as a pre-activation output. You will apply activation functions to this output.

torch.nn is already imported as nn.
"""

# Instructions

"""
Create a sigmoid function and apply it on the score tensor to generate a probability.

Create a softmax function and apply it on the score tensor to generate a probability.
"""

# solution

score = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on the score tensor
sigmoid = nn.Sigmoid()
probability = sigmoid(score)
print(probability)

#----------------------------------#

scores = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

# Create a softmax function and apply it on the score tensor
softmax = nn.Softmax(dim = -1)
probabilities = softmax(scores)
print(probabilities)

#----------------------------------#

# Conclusion

"""
Nice work! In subsequent lessons, we'll work on using nn.Sequential() to directly add linear layers, as well as the nn.Softmax() or nn.Sigmoid() activation functions to neural networks.
"""

tensor([[0.6900]])
tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


"\nNice work! In subsequent lessons, we'll work on using nn.Sequential() to directly add linear layers, as well as the nn.Softmax() or nn.Sigmoid() activation functions to neural networks.\n"