In [2]:
# run this to shorten the data import from the files
path_data = ''


In [3]:
# exercise 01

"""
Create an array

You can use the NumPy package to create arrays. NumPy arrays are optimized for numerical analyses and contain only a single data type. To convert a list to an array, you can use the array() function from NumPy.

import numpy as np

a_list = [1, 2, 3, 4]
a_list

[1, 2, 3, 4]

an_array = np.array(a_list)
an_array

array([1, 2, 3, 4])

"""

# Instructions

"""

    Import numpy using the alias np.
    Create prices_array and earnings_array arrays from the lists prices and earnings, respectively.

"""

# solution

# Import numpy as np
import numpy as np

# Lists
prices = [170.12, 93.29, 55.28, 145.30, 171.81, 59.50, 100.50]
earnings = [9.2, 5.31, 2.41, 5.91, 15.42, 2.51, 6.79]

# NumPy arrays
prices_array = np.array(prices)
earnings_array = np.array(earnings)

# Print the arrays
print(prices_array)
print(earnings_array)

#----------------------------------#

# Conclusion

"""
Nice job! In the next exercise you will see how easy it is to perform mathematical operations on arrays.
"""

[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]


'\nNice job! In the next exercise you will see how easy it is to perform mathematical operations on arrays.\n'

In [4]:
# exercise 02

"""
Elementwise operations on arrays

Arrays allow for efficient numerical manipulation of its elements. Let's explore element-wise mathematical operations by calculating price to earnings ratio using two arrays, prices_array and earnings_array from the previous exercise.

This price to earnings ratio, or PE ratio, is a financial indicator of the dollar amount an investor can expect to invest in a company in order to receive one dollar of that company’s earnings.

prices_array and earnings_array are available in your workspace.
"""

# Instructions

"""

    Import numpy as np.
    Create pe_array by dividing prices_array by earnings_array.

"""

# solution

# Import numpy as np
import numpy as np

# Create PE ratio array
pe_array = np.array(prices_array/earnings_array)

# Print pe_array
print(pe_array)

#----------------------------------#

# Conclusion

"""
Nice! It's time to subset NumPy arrays.
"""

[18.49130435 17.56873823 22.93775934 24.58544839 11.14202335 23.70517928
 14.8011782 ]


"\nNice! It's time to subset NumPy arrays.\n"

In [14]:
# exercise 03

"""
Subsetting elements from an array

Subsetting arrays is similar to subsetting lists. In this exercise, you will practice just that.

numpy is imported as np and prices_array is available in your workspace.
"""

# Instructions

"""
Subset the first three elements from prices_array.
---
Subset the last three elements from the prices_array using negative index slicing.
---
Subset every third element from the prices_array using step slicing.
"""

# solution

# Subset the first three elements
prices_subset_1 = prices_array[:3]
print(prices_subset_1)

#----------------------------------#

# Subset last three elements 
prices_subset_2 = prices_array[-3:]
print(prices_subset_2)

#----------------------------------#

# Subset every third element
prices_subset_3 = prices_array[0:7:3]
print(prices_subset_3)

#----------------------------------#

# Conclusion

"""
Great job! It's time to learn about 2-D NumPy arrays.
"""

[170.12  93.29  55.28]
[171.81  59.5  100.5 ]
[170.12 145.3  100.5 ]


"\nGreat job! It's time to learn about 2-D NumPy arrays.\n"

In [16]:
# exercise 04

"""
Creating a 2D array

Multi-dimensional arrays can be useful for several tasks. In finance, for example, a 2D array may be used to store the prices and earnings for various companies. Let's create this 2D array, stock_array, from a list of prices and earnings.

numpy is imported as np and the two lists prices and earnings are available in your workspace.
"""

# Instructions

"""

    Create a two dimensional array of prices and earnings (in that order) and assign it to stock_array.
    Print the shape of stock_array.
---

    Transpose stock_array and assign the result to stock_array_transposed.
    Print the size of stock_array_transposed.

"""
# solution

# Create a 2D array of prices and earnings
stock_array = np.array([prices,earnings])
print(stock_array)

# Print the shape of stock_array
print(stock_array.shape)

# Print the size of stock_array
print(stock_array.size)

#----------------------------------#


# Transpose stock_array
stock_array_transposed = np.transpose(stock_array)
print(stock_array_transposed)

# Print the shape of stock_array
print(stock_array_transposed.shape)

# Print the size of stock_array
print(stock_array_transposed.size)

#----------------------------------#

# Conclusion

"""
Nice! Did you notice that transposing changes only the shape of the array, but not it's size?
"""

[[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
 [  9.2    5.31   2.41   5.91  15.42   2.51   6.79]]
(2, 7)
14
[[170.12   9.2 ]
 [ 93.29   5.31]
 [ 55.28   2.41]
 [145.3    5.91]
 [171.81  15.42]
 [ 59.5    2.51]
 [100.5    6.79]]
(7, 2)
14


"\nNice! Did you notice that transposing changes only the shape of the array, but not it's size?\n"

In [17]:
# exercise 05

"""
Subsetting 2D arrays

Subsetting 2D arrays is similar to subsetting nested lists. In a 2D array, the indexing or slicing must be specific to the dimension of the array:

array[row_index, column_index]

numpy is imported as np and the 2D array stock_array_transposed (from the previous exercise) is available in your workspace.
"""

# Instructions

"""
Extract the first column from stock_array_transposed and assign it to prices.
---
Extract the second column from stock_array_transposed and assign it to earnings.
---
Subset the price and earning of the first company (row 0) from stock_array_transposed and assign it to company_1.
"""

# solution

# Subset prices from stock_array_transposed
prices = stock_array_transposed[:, 0]
print(prices)

#----------------------------------#

# Subset earnings from stock_array_transposed
earnings = stock_array_transposed[:,1]
print(earnings)

#----------------------------------#

# Subset the price and earning for first company
company_1 = stock_array_transposed[0,0:]
print(company_1)

#----------------------------------#

# Conclusion

"""
Nice job! It's time to calculate summary stats of arrays.
"""

[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]
[170.12   9.2 ]


"\nNice job! It's time to calculate summary stats of arrays.\n"

In [18]:
# exercise 06

"""
Calculating array stats

Not only can you perform elementwise calculations on NumPy arrays, you can also calculate summary stats such as mean and standard deviation of arrays using functions from NumPy.

numpy is imported as np and the array prices (from the previous exercise) is available in your workspace.
"""

# Instructions

"""
Calculate the mean of prices.
---
Calculate the standard deviation of prices.
"""

# solution

# Calculate the mean 
prices_mean = np.mean(prices)
print(prices_mean)

#----------------------------------#

# Calculate the standard deviation 
prices_std = np.std(prices)
print(prices_std)

#----------------------------------#

# Conclusion

"""
Excellent! In the next exercise, you will generate a sequence of numbers.
"""

113.6857142857143
45.51277932221513


'\nExcellent! In the next exercise, you will generate a sequence of numbers.\n'

In [19]:
# exercise 07

"""
Generating a sequence of numbers

You may want to create an array of a range of numbers (e.g., 1 to 10) without having to type in every single number. The NumPy function arange() is an efficient way to create numeric arrays of a range of numbers. The arguments for arange() include the start, stop, and step interval as shown below:

np.arange(start, stop, step)

numpy is imported as np.
"""

# Instructions

"""

    Create an array company_ids containing the numbers 1 through 7 (inclusive).
    Create an array company_ids_odd containing only the odd numbers from 1 through 7 (inclusive).

"""

# solution

# Create and print company IDs
company_ids = np.arange(1, 8, 1)
print(company_ids)

# Use array slicing to select specific company IDs
company_ids_odd = np.arange(1, 8, 2)
print(company_ids_odd)

#----------------------------------#

# Conclusion

"""
Great job! Using arange() can be much faster than typing each individual element.
"""

[1 2 3 4 5 6 7]
[1 3 5 7]


'\nGreat job! Using arange() can be much faster than typing each individual element.\n'

In [20]:
# exercise 08

"""
Who's above average?

Boolean arrays can be a very powerful way to subset arrays. In this exercise, you will identify the prices that are greater than average from a list of prices.

numpy is imported as np and the array prices is available in your workspace.
"""

# Instructions

"""

    Find elements in prices that are greater than price_mean and assign the boolean result to boolean_array.
    Subset prices using boolean_array and assign the result to above_avg.

"""

# solution

# Find the mean
price_mean = np.mean(prices)

# Create boolean array
boolean_array = (prices > price_mean)
print(boolean_array)

# Select prices that are greater than average
above_avg = prices[boolean_array]
print(above_avg)

#----------------------------------#

# Conclusion

"""
Great work! In the next exercise, you will use boolean arrays to find the companies in the health care sector.
"""

[ True False False  True  True False False]
[170.12 145.3  171.81]


'\nGreat work! In the next exercise, you will use boolean arrays to find the companies in the health care sector.\n'

In [21]:
# exercise 09

"""
Who's in health care?

In this exercise, you are provided the names of companies with their associated sector, and your goal is to find all companies that are associated with health care sector.

numpy is imported as np and the arrays names and sectors are available in your workspace.
"""

# Instructions

"""

    Find elements in sectors that are equivalent to 'Health Care' and assign the result to boolean_array.
    Subset names using boolean_array and assign the result to health_care.

"""
sectors = np.array(['Information Technology', 'Health Care', 'Health Care',
       'Information Technologies', 'Health Care'])
names = np.array(['Apple Inc', 'Abbvie Inc', 'Abbott Laboratories',
       'Accenture Technologies', 'Allergan Plc'])
# solution

# Create boolean array
boolean_array = (sectors == 'Health Care')
print(boolean_array)

# Print only health care companies
health_care = names[boolean_array]
print(health_care)

#----------------------------------#

# Conclusion

"""
Well done! In the next chapter you will learn about visualization.
"""

[False  True  True False  True]
['Abbvie Inc' 'Abbott Laboratories' 'Allergan Plc']


'\nWell done! In the next chapter you will learn about visualization.\n'