In [1]:
# run this to shorten the data import from the files
import os
path_data = os.path.join(os.path.dirname(os.getcwd()), 'datasets/')


In [4]:
import torch

input_layer = torch.tensor([[ 0.0401, -0.9005,  0.0397, -0.0876]])

weight_1 = torch.tensor([[-0.1094, -0.8285,  0.0416, -1.1222],[ 0.3327, -0.0461,  1.4473, -0.8070],[ 0.0681, -0.7058, -1.8017,  0.5857],[ 0.8764,  0.9618, -0.4505,  0.2888]])

weight_2 = torch.tensor([[ 0.6856, -1.7650,  1.6375, -1.5759],
        [-0.1092, -0.1620,  0.1951, -0.1169],
        [-0.5120,  1.1997,  0.8483, -0.2476],
        [-0.3369,  0.5617, -0.6658,  0.2221]])

weight_3 = torch.tensor([[ 0.8824,  0.1268,  1.1951,  1.3061],
        [-0.8753, -0.3277, -0.1454, -0.0167],
        [ 0.3582,  0.3254, -1.8509, -1.4205],
        [ 0.3786,  0.5999, -0.5665, -0.3975]])

In [5]:
# exercise 01

"""
Neural networks

Let us see the differences between neural networks which apply ReLU and those which do not apply ReLU. We have already initialized the input called input_layer, and three sets of weights, called weight_1, weight_2 and weight_3.

We are going to convince ourselves that networks with multiple layers which do not contain non-linearity can be expressed as neural networks with one layer.

The network and the shape of layers and weights is shown below.


"""

# Instructions

"""

    Calculate the first and second hidden layer by multiplying the appropriate inputs with the corresponding weights.
    Calculate and print the results of the output.
    Set weight_composed_1 to the product of weight_1 with weight_2, then set weight to the product of weight_composed_1 with weight_3.
    Calculate and print the output.

"""

# solution

# Calculate the first and second hidden layer
hidden_1 = torch.matmul(input_layer, weight_1)
hidden_2 = torch.matmul(hidden_1, weight_2)

# Calculate the output
print(torch.matmul(hidden_2, weight_3))

# Calculate weight_composed_1 and weight
weight_composed_1 = torch.matmul(weight_1, weight_2)
weight = torch.matmul(weight_composed_1, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

#----------------------------------#

# Conclusion

"""
Good job! You see how the results are the same.
"""

tensor([[0.2653, 0.1311, 3.8219, 3.0032]])
tensor([[0.2653, 0.1311, 3.8219, 3.0032]])


'\nGood job! You see how the results are the same.\n'

In [8]:
# exercise 02

"""
ReLU activation

In this exercise, we have the same settings as the previous exercise. But now we are going to build a neural network which has non-linearity. By doing so, we are going to convince ourselves that networks with multiple layers and non-linearity functions cannot be expressed as a neural network with one layer.

We have already instantiated the ReLU activation function called relu() for you.
"""

# Instructions

"""

    Apply the non-linearity to the two hidden layers and print the result.
    Apply the non-linearity to the product of first two weights.
    Multiply the result of the previous step with weight_3.
    Multiply input_layer with weight and print the results.

"""

# solution
import torch.nn as nn

# Instantiate non-linearity
relu = nn.ReLU()

# Apply non-linearity on the hidden layers
hidden_1_activated = relu(torch.matmul(input_layer, weight_1))
hidden_2_activated = relu(torch.matmul(hidden_1_activated, weight_2))
print(torch.matmul(hidden_2_activated, weight_3))

# Apply non-linearity in the product of first two weights. 
weight_composed_1_activated = relu(torch.matmul(weight_1, weight_2))

# Multiply `weight_composed_1_activated` with `weight_3
weight = torch.matmul(weight_composed_1_activated, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

#----------------------------------#

# Conclusion

"""
Awesome! As expected, the results are different from the previous exercise.
"""

tensor([[-0.2770, -0.0345, -0.1410, -0.0664]])
tensor([[-0.2117, -0.4782,  4.0438,  3.0417]])


'\nAwesome! As expected, the results are different from the previous exercise.\n'

In [9]:
# exercise 03

"""
ReLU activation again

Neural networks don't need to have the same number of units in each layer. Here, you are going to experiment with the ReLU activation function again, but this time we are going to have a different number of units in the layers of the neural network. The input layer will still have 4 features, but then the first hidden layer will have 6 units and the output layer will have 2 units.


"""

# Instructions

"""

    Instantiate the ReLU() activation function as relu (the function is part of nn module).
    Initialize weight_1 and weight_2 with random numbers.
    Multiply the input_layer with weight_1, storing results in hidden_1.
    Apply the relu activation function over hidden_1, and then multiply the output of it with weight_2.

"""

# solution

# Instantiate ReLU activation function as relu
relu = nn.ReLU()

# Initialize weight_1 and weight_2 with random numbers
weight_1 = torch.rand(4, 6)
weight_2 = torch.rand(6, 2)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Apply ReLU activation function over hidden_1 and multiply with weight_2
hidden_1_activated = relu(hidden_1)
print(torch.matmul(hidden_1_activated, weight_2))

#----------------------------------#

# Conclusion

"""
Great! You can now build neural networks with different number of neurons on each layer.
"""

tensor([[0., 0.]])


'\nGreat! You can now build neural networks with different number of neurons on each layer.\n'

In [26]:
# exercise 04

"""
Calculating loss function by hand

Let's start the exercises by calculating the loss function by hand. Don't do this exercise in PyTorch, it is important to first do it using only pen and paper (and a calculator).

We have the same example as before but now our object is actually a frog, and the predicted scores are -1.2 for class 0 (cat), 0.12 for class 1 (car) and 4.8 for class 2 (frog).

What is the result of the softmax cross-entropy loss function?
Class 	Predicted Score
Cat 	-1.2
Car 	0.12
Frog 	4.8
"""

# Instructions

"""
Possible Answers

    6.0117

    4.6917

    0.0117

    Score for frog is high, so loss is 0.
"""

# solution
import numpy as np

# Calculate normalized softmax
def softmax_std(f):
    f = f - np.max(f)
    prob = np.exp(f) / np.sum(np.exp(f))
    return prob

# Calculate cross-entropy loss
def cross_entropy_loss(y_pred, y_true):

    # Calcualte the softmax array
    soft = softmax_std(y_pred)
    # Initialize the loss value
    loss = 0

    # The loss for each class is calculated by the formula Loss = -Y_true * log(Y_pred)
    # The step -1 * y_true[i] adjusts the -Y_true to the  correct value in the array
    # The total loss is the sum of all the losses
    for i in range(len(soft)):
        # Calculate and add the loss value for each prediction
        loss = loss + (-1 * y_true[i] * np.log(soft[i]))
    
    return loss

true_pred = [0,0,1] # Cat, Car, Frog
pred_array = np.array([-1.2, 0.12, 4.8])

loss = cross_entropy_loss(pred_array, true_pred)
print(f'The loss is {loss}')

#----------------------------------#

# Conclusion

"""
Congratulations, you computed correctly the softmax cross-entropy loss. You rock!
"""

The loss is 0.01168918061661097


'\nCongratulations, you computed correctly the softmax cross-entropy loss. You rock!\n'

In [27]:
# exercise 05

"""
Calculating loss function in PyTorch

You are going to code the previous exercise, and make sure that we computed the loss correctly. Predicted scores are -1.2 for class 0 (cat), 0.12 for class 1 (car) and 4.8 for class 2 (frog). The ground truth is class 2 (frog). Compute the loss function in PyTorch.
Class 	Predicted Score
Cat 	-1.2
Car 	0.12
Frog 	4.8
"""

# Instructions

"""

    Initialize the tensor of scores with numbers [[-1.2, 0.12, 4.8]], and the tensor of ground truth [2].
    Instantiate the cross-entropy loss and call it criterion.
    Compute and print the loss.

"""

# solution

# Initialize the scores and ground truth
logits = torch.tensor([[-1.2, 0.12, 4.8]])
ground_truth = torch.tensor([2])

# Instantiate cross entropy loss
criterion = nn.CrossEntropyLoss()

# Compute and print the loss
loss = criterion(logits, ground_truth)
print(loss)

#----------------------------------#

# Conclusion

"""
As you can see, the loss function PyTorch calculated gives the same number as the loss function you calculated. Being proficient in understanding and calculating loss functions is a very important skill in deep learning.
"""

tensor(0.0117)


'\nAs you can see, the loss function PyTorch calculated gives the same number as the loss function you calculated. Being proficient in understanding and calculating loss functions is a very important skill in deep learning.\n'

In [31]:
# exercise 06

"""
Loss function of random scores

If the neural network predicts random scores, what would be its loss function? Let's find it out in PyTorch. The neural network is going to have 1000 classes, each having a random score. For ground truth, it will have class 111. Calculate the loss function.
"""

# Instructions

"""

    Import torch and torch.nn as nn
    Initialize logits with a random tensor of shape (1, 1000) and ground_truth with a tensor containing the number 111.
    Instantiate the cross-entropy loss in a variable called criterion.
    Calculate and print the loss function.

"""

# solution

# Import torch and torch.nn
import torch
import torch.nn as nn

# Initialize logits and ground truth
logits = torch.rand(1,1000)
ground_truth = torch.tensor([111])

# Instantiate cross-entropy loss
criterion = nn.CrossEntropyLoss()

# Calculate and print the loss
loss = criterion(logits, ground_truth)
print(loss)

#----------------------------------#

# Conclusion

"""
The score is close to -ln(1/1000) = 6.9. This is not surprising, considering that scores were random and close to each other, so the probability for each class was approximately the same (1/1000) = 0.001.
"""

tensor(6.6232)


'\nThe score is close to -ln(1/1000) = 6.9. This is not surprising, considering that scores were random and close to each other, so the probability for each class was approximately the same (1/1000) = 0.001.\n'

In [32]:
# exercise 07

"""
Preparing MNIST dataset

You are going to prepare dataloaders for MNIST training and testing set. As we explained in the lecture, MNIST has some differences to CIFAR-10, with the main difference being that MNIST images are grayscale (1 channel based) instead of RGB (3 channels).
"""

# Instructions

"""

    Transform the data to torch tensors and normalize it to have mean is 0.1307 and std is 0.3081.
    Prepare the trainset and the testset.
    Prepare the dataloaders for training and testing so that only 32 pictures are processed at a time and the training data is shuffled each time.

"""
import torch
import torchvision
import torch.utils.data
import torchvision.transforms as transforms

# solution

# Transform the data to torch tensors and normalize it 
# The Normalize recives the mean and std for each channel
transform = transforms.Compose([transforms.ToTensor(),
								transforms.Normalize((0.1307), ((0.3081)))])

# Prepare training set and testing set
trainset = torchvision.datasets.MNIST('/run/media/nero/e753e46e-c457-4237-9670-c71cee45c7bc/Datasets/torchvision/', train=True, 
									  download=True, transform=transform)
testset = torchvision.datasets.MNIST('/run/media/nero/e753e46e-c457-4237-9670-c71cee45c7bc/Datasets/torchvision/', train=False, 
									  download=True, transform=transform)

# Prepare training loader and testing loader
trainloader = torch.utils.data.DataLoader(trainset, batch_size=32,
                                          shuffle=True, num_workers=4)
testloader = torch.utils.data.DataLoader(testset, batch_size=32,
										 shuffle=False, num_workers=4) 

#----------------------------------#

# Conclusion

"""
Nice! Now you know how to prepare datasets in PyTorch. You are very close to reaching the grand goal, training neural networks!
"""

100%|██████████| 9912422/9912422 [00:19<00:00, 513307.71it/s]


Extracting /run/media/nero/e753e46e-c457-4237-9670-c71cee45c7bc/Datasets/torchvision/MNIST/raw/train-images-idx3-ubyte.gz to /run/media/nero/e753e46e-c457-4237-9670-c71cee45c7bc/Datasets/torchvision/MNIST/raw



100%|██████████| 28881/28881 [00:00<00:00, 15922146.93it/s]

Extracting /run/media/nero/e753e46e-c457-4237-9670-c71cee45c7bc/Datasets/torchvision/MNIST/raw/train-labels-idx1-ubyte.gz to /run/media/nero/e753e46e-c457-4237-9670-c71cee45c7bc/Datasets/torchvision/MNIST/raw



100%|██████████| 1648877/1648877 [00:04<00:00, 408130.87it/s]


Extracting /run/media/nero/e753e46e-c457-4237-9670-c71cee45c7bc/Datasets/torchvision/MNIST/raw/t10k-images-idx3-ubyte.gz to /run/media/nero/e753e46e-c457-4237-9670-c71cee45c7bc/Datasets/torchvision/MNIST/raw



100%|██████████| 4542/4542 [00:00<00:00, 1828265.72it/s]

Extracting /run/media/nero/e753e46e-c457-4237-9670-c71cee45c7bc/Datasets/torchvision/MNIST/raw/t10k-labels-idx1-ubyte.gz to /run/media/nero/e753e46e-c457-4237-9670-c71cee45c7bc/Datasets/torchvision/MNIST/raw



'\nNice! Now you know how to prepare datasets in PyTorch. You are very close to reaching the grand goal, training neural networks!\n'

In [36]:
# exercise 08

"""
Inspecting the dataloaders

Now you are going to explore a bit the dataloaders you created in the previous exercise. In particular, you will compute the shape of the dataset in addition to the minibatch size.
"""

# Instructions

"""

    Find the shapes of the trainset and testset.
    Print the computed values.
    Find the size of the minibatch for both trainset and testset.
    Print the minibatch size.

"""

# solution

# Compute the shape of the training set and testing set
trainset_shape = trainloader.dataset.data.shape
testset_shape = testloader.dataset.data.shape

# Print the computed shapes
print(trainset_shape, testset_shape)

# Compute the size of the minibatch for training set and testing set
trainset_batchsize = trainloader.batch_size
testset_batchsize =testloader.batch_size

# Print sizes of the minibatch
print(trainset_batchsize, testset_batchsize)

#----------------------------------#

# Conclusion

"""
After you have armed yourself with the knowledge of building and exploring dataloaders, it is time to start training neural networks!
"""

torch.Size([60000, 28, 28]) torch.Size([10000, 28, 28])
32 32


'\nAfter you have armed yourself with the knowledge of building and exploring dataloaders, it is time to start training neural networks!\n'

In [37]:
# exercise 09

"""
Building a neural network - again

You haven't created a neural network since the end of the first chapter, so this is a good time to build one (practice makes perfect). Build a class for a neural network which will be used to train on the MNIST dataset. The dataset contains images of shape (28, 28, 1), so you should deduct the size of the input layer. For hidden layer use 200 units, while for output layer use 10 units (1 for each class). For activation function, use relu in a functional way (nn.Functional is already imported as F).

For context, the same net will be trained and used to make predictions in the next two exercises.
"""

# Instructions

"""

    Define the class called Net which inherits from nn.Module.
    In the __init__() method, define the parameters for the two fully connected layers.
    In the .forward() method, do the forward step.

"""

# solution

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# Define the class Net
class Net(nn.Module) :
    def __init__(self):    
    	# Define all the parameters of the net
        super(Net, self).__init__()
        self.fc1 = nn.Linear(28 * 28 * 1, 200)
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):   
    	# Do the forward pass
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

#----------------------------------#

# Conclusion

"""
Great! You have not forgotten how to build neural networks.
"""

'\nGreat! You have not forgotten how to build neural networks.\n'

In [39]:
# exercise 10

"""
Training a neural network

Given the fully connected neural network (called model) which you built in the previous exercise and a train loader called train_loader containing the MNIST dataset (which we created for you), you're to train the net in order to predict the classes of digits. You will use the Adam optimizer to optimize the network, and considering that this is a classification problem you are going to use cross entropy as loss function.
"""

# Instructions

"""

    Instantiate the Adam optimizer with learning rate 3e-4 and instantiate Cross-Entropy as loss function.
    Complete a forward pass on the neural network using the input data.
    Using backpropagation, compute the gradients of the weights, and then change the weights using the Adam optimizer.

"""

# solution

# Instantiate the Adam optimizer and Cross-Entropy loss function
model = Net()   
optimizer = optim.Adam(model.parameters(), lr=3e-4)
criterion = nn.CrossEntropyLoss()
  
for batch_idx, data_target in enumerate(trainloader):
    data = data_target[0]
    target = data_target[1]
    data = data.view(-1, 28 * 28)
    optimizer.zero_grad()

    # Complete a forward pass
    output = model(data)

    # Compute the loss, gradients and change the weights
    loss = criterion(output, target)
    loss.backward()
    optimizer.step()

#----------------------------------#

# Conclusion

"""
Fantastic! Now you can train neural networks.
"""

/home/nero/Documents/Estudos/estudos/lib/python3.11/site-packages/torch/autograd/__init__.py:200: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass


'\nFantastic! Now you can train neural networks.\n'

In [41]:
# exercise 11

"""
Using the network to make predictions

Now that you have trained the network, use it to make predictions for the data in the testing set. The network is called model (same as in the previous exercise), and the loader is called test_loader. We have already initialized variables total and correct to 0.
"""

# Instructions

"""

    Set the network in testing (eval) mode.
    Put each image into a vector using inputs.view(-1, number_of_features) where the number of features should be deducted by multiplying spatial dimensions (shape) of the image.
    Do the forward pass and put the predictions in output variable.

"""

# solution
total = 0
correct = 0

# Set the model in eval mode
model.eval()

for i, data in enumerate(testloader, 0):
    inputs, labels = data
    
    # Put each image into a vector
    inputs = inputs.view(-1, 28*28*1)
    
    # Do the forward pass and get the predictions
    outputs = model(inputs)
    _, outputs = torch.max(outputs.data, 1)
    total += labels.size(0)
    correct += (outputs == labels).sum().item()
print('The testing set accuracy of the network is: %d %%' % (100 * correct / total))

#----------------------------------#

# Conclusion

"""
Congratulations, you are able to use neural networks to make predictions. NB: The accuracy of the net is too low compared to what we can do with neural networks. We used only a subpart of the dataset in order for the training to happen fast. You can achieve a much higher accuracy by using the entire dataset, and by using a larger neural network.
"""

The testing set accuracy of the network is: 95 %


'\nCongratulations, you are able to use neural networks to make predictions. NB: The accuracy of the net is too low compared to what we can do with neural networks. We used only a subpart of the dataset in order for the training to happen fast. You can achieve a much higher accuracy by using the entire dataset, and by using a larger neural network.\n'