In [1]:
# run this to shorten the data import from the files
import os
path_data = os.path.join(os.path.dirname(os.getcwd()), 'datasets/')


In [2]:
# exercise 01

"""
Creating tensors in PyTorch

Random tensors are very important in neural networks. Parameters of the neural networks typically are initialized with random weights (random tensors).

Let us start practicing building tensors in PyTorch library. As you know, tensors are arrays with an arbitrary number of dimensions, corresponding to NumPy's ndarrays. You are going to create a random tensor of sizes 3 by 3 and set it to variable your_first_tensor. Then, you will need to print it. Finally, calculate its size in variable tensor_size and print its value.

NB: In case you have trouble solving the problems, you can always refer to slides in the bottom right of the screen.
"""

# Instructions

"""

    Import PyTorch main library.
    Create the variable your_first_tensor and set it to a random torch tensor of size 3 by 3.
    Calculate its shape (dimension sizes) and set it to variable tensor_size.
    Print the values of your_first_tensor and tensor_size.

"""

# solution

# Import torch
import torch

# Create random tensor of size 3 by 3
your_first_tensor = torch.rand(3, 3)

# Calculate the shape of the tensor
tensor_size = your_first_tensor.shape

# Print the values of the tensor and its shape
print(your_first_tensor)
print(tensor_size)

#----------------------------------#

# Conclusion

"""
Congratulations! You just built your first PyTorch tensor.
"""

tensor([[0.1972, 0.5827, 0.5850],
        [0.3790, 0.2765, 0.3951],
        [0.3014, 0.6026, 0.3332]])
torch.Size([3, 3])


'\nCongratulations! You just built your first PyTorch tensor.\n'

In [3]:
# exercise 02

"""
Matrix multiplication

There are many important types of matrices which have their uses in neural networks. Some important matrices are matrices of ones (where each entry is set to 1) and the identity matrix (where the diagonal is set to 1 while all other values are 0). The identity matrix is very important in linear algebra: any matrix multiplied with identity matrix is simply the original matrix.

Let us experiment with these two types of matrices. You are going to build a matrix of ones with shape 3 by 3 called tensor_of_ones and an identity matrix of the same shape, called identity_tensor. We are going to see what happens when we multiply these two matrices, and what happens if we do an element-wise multiplication of them.
"""

# Instructions

"""

    Create a matrix of ones with shape 3 by 3, and put it on variable tensor_of_ones.
    Create an identity matrix with shape 3 by 3, and put it on variable identity_tensor.
    Do a matrix multiplication of tensor_of_ones with identity_tensor and print its value.
    Do an element-wise multiplication of tensor_of_ones with identity_tensor and print its value.

"""

# solution

# Create a matrix of ones with shape 3 by 3
tensor_of_ones = torch.ones(3, 3)

# Create an identity matrix with shape 3 by 3
identity_tensor = torch.eye(3)

# Do a matrix multiplication of tensor_of_ones with identity_tensor
matrices_multiplied = torch.matmul(tensor_of_ones, identity_tensor)
print(matrices_multiplied)

# Do an element-wise multiplication of tensor_of_ones with identity_tensor
element_multiplication = tensor_of_ones * identity_tensor
print(element_multiplication)

#----------------------------------#

# Conclusion

"""
Interesting! matrices_multiplied is same as tensor_of_ones (because identity matrix is the neutral element in matrix multiplication, the product of any matrix multiplied with it gives the original matrix), while element_multiplication is same as identity_tensor.
"""

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


'\nInteresting! matrices_multiplied is same as tensor_of_ones (because identity matrix is the neutral element in matrix multiplication, the product of any matrix multiplied with it gives the original matrix), while element_multiplication is same as identity_tensor.\n'

In [4]:
# exercise 03

"""
Forward pass

Let's have something resembling more a neural network. The computational graph has been given below. You are going to initialize 3 large random tensors, and then do the operations as given in the computational graph. The final operation is the mean of the tensor, given by torch.mean(your_tensor).


"""

# Instructions

"""

    Initialize random tensors x, y and z, each having shape (1000, 1000).
    Multiply x with y, putting the result in tensor q.
    Do an elementwise multiplication of tensor z with tensor q, putting the results in f

"""

# solution

# Initialize tensors x, y and z
x = torch.rand(1000, 1000)
y = torch.rand(1000, 1000)
z = torch.rand(1000, 1000)

# Multiply x with y
q = torch.matmul(x, y)

# Multiply elementwise z with q
f = torch.matmul(z, q)

mean_f = torch.mean(f)
print(mean_f)

#----------------------------------#

# Conclusion

"""
You just built a nice computational graph containing 5'000'001 values. In the next lesson, you are going to compute the gradients of this graph.
"""

tensor(125121.6406)


"\nYou just built a nice computational graph containing 5'000'001 values. In the next lesson, you are going to compute the gradients of this graph.\n"

In [5]:
# exercise 04

"""
Backpropagation by hand

Given the computational graph above, we want to calculate the derivatives for the leaf nodes (x, y and z). To get you started we already calculated the results of the forward pass (in red) in addition to calculating the derivatives of f and q.

The rules for derivative computations have been given in the table below:
Interaction 	Overall Change
Addition 	(f+g)' = f' + g'
Multiplication 	(f \cdot g)' = f \cdot dg + g \cdot df
Powers 	(x^n)' = \frac{d}{dx}x^n = nx^{n-1}
Inverse 	(\frac{1}{x})' = - \frac{1}{x^2}
Division 	(\frac{f}{g})' = (df \cdot \frac{1}{g}) + (\frac{-1}{g^2}dg \cdot f)

"""

# Instructions

"""
The Derivative of x is 5, the derivative of y is 5, the derivative of z is 1. (Answer)


The Derivative of x is 5, the derivative of y is 5, the derivative of z is 5.


The Derivative of x is 8, the derivative of y is -3, the derivative of z is 0.


Derivatives are lame, integrals are cool.


"""

# solution



#----------------------------------#

# Conclusion

"""
Congratulations, you know how to compute derivatives! While PyTorch computes derivatives for you, mastering them will make you a much better deep learning practitioner and that knowledge will guide you in training neural networks better.
"""

'\nCongratulations, you know how to compute derivatives! While PyTorch computes derivatives for you, mastering them will make you a much better deep learning practitioner and that knowledge will guide you in training neural networks better.\n'

In [7]:
# exercise 05

"""
Backpropagation using PyTorch

Here, you are going to use automatic differentiation of PyTorch in order to compute the derivatives of x, y and z from the previous exercise.
"""

# Instructions

"""

    Initialize tensors x, y and z to values 4, -3 and 5.
    Put the sum of tensors x and y in q, put the product of q and z in f.
    Calculate the derivatives of the computational graph.
    Print the gradients of the x, y and z tensors.

"""

# solution

# Initialize x, y and z to values 4, -3 and 5
x = torch.tensor(4., requires_grad = True)
y = torch.tensor(-3., requires_grad = True)
z = torch.tensor(5., requires_grad = True)

# Set q to sum of x and y, set f to product of q with z
q = x + y
f = q * z

# Compute the derivatives
f.backward()

# Print the gradients
print("Gradient of x is: " + str(x.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of z is: " + str(z.grad))

#----------------------------------#

# Conclusion

"""
No surprise here, the results are the same as when you calculated them by hand!
"""

Gradient of x is: tensor(5.)
Gradient of y is: tensor(5.)
Gradient of z is: tensor(1.)


'\nNo surprise here, the results are the same as when you calculated them by hand!\n'

In [12]:
# exercise 06

"""
Calculating gradients in PyTorch

Remember the exercise in forward pass? Now that you know how to calculate derivatives, let's make a step forward and start calculating the gradients (derivatives of tensors) of the computational graph you built back then. We have already initialized for you three random tensors of shape (1000, 1000) called x, y and z. First, we multiply tensors x and y, then we do an elementwise multiplication of their product with tensor z, and then we compute its mean. In the end, we compute the derivatives.

The main difference from the previous exercise is the scale of the tensors. While before, tensors x, y and z had just 1 number, now they each have 1 million numbers.


"""

# Instructions

"""

    Multiply tensors x and y, put the product in tensor q.
    Do an elementwise multiplication of tensors z with q.
    Calculate the gradients.

"""

# solution

x = torch.rand(1000,1000, requires_grad=True)
y = torch.rand(1000,1000, requires_grad=True)
z = torch.rand(1000,1000, requires_grad=True)

# Multiply tensors x and y
q = torch.matmul(x, y)

# Elementwise multiply tensors z with q
f = torch.matmul(z, q)

mean_f = torch.mean(f)

# Calculate the gradients
mean_f.backward()

#----------------------------------#

# Conclusion

"""
In general, calculating gradients is as easy as calculating derivatives in PyTorch. Obviously, if the tensors are very large (billions of values) then the calculation might take some time.
"""

'\nIn general, calculating gradients is as easy as calculating derivatives in PyTorch. Obviously, if the tensors are very large (billions of values) then the calculation might take some time.\n'

In [13]:
# exercise 07

"""
Your first neural network

You are going to build a neural network in PyTorch, using the hard way. Your input will be images of size (28, 28), so images containing 784 pixels. Your network will contain an input_layer (provided for you), a hidden layer with 200 units, and an output layer with 10 classes. The input layer has already been created for you. You are going to create the weights, and then do matrix multiplications, getting the results from the network.
"""

# Instructions

"""

    Initialize with random numbers two matrices of weights, called weight_1 and weight_2.
    Set the result of input_layer times weight_1 to hidden_1. Set the result of hidden_1 times weight_2 to output_layer.

"""

# solution

input_layer = torch.rand(1, 784)

# Initialize the weights of the neural network
weight_1 = torch.rand(784, 200)
weight_2 = torch.rand(200, 10)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Multiply hidden_1 with weight_2
output_layer = torch.matmul(hidden_1, weight_2)
print(output_layer)

#----------------------------------#

# Conclusion

"""
For the most part, neural networks are just matrix (tensor) multiplication. This is the reason why we have put so much emphasis on matrices and tensors!
"""

tensor([[18966.3789, 18745.3770, 20095.6758, 20571.6602, 19169.6055, 20590.2129,
         18754.4414, 16813.2090, 19097.8398, 18202.1953]])


'\nFor the most part, neural networks are just matrix (tensor) multiplication. This is the reason why we have put so much emphasis on matrices and tensors!\n'

In [14]:
# exercise 08

"""
Your first PyTorch neural network

You are going to build the same neural network you built in the previous exercise, but now using the PyTorch way. As a reminder, you have 784 units in the input layer, 200 hidden units and 10 units for the output layer.
"""

# Instructions

"""

    Instantiate two linear layers calling them self.fc1 and self.fc2. Determine their correct dimensions.
    Implement the .forward() method, using the two layers you defined and returning x.

"""

# solution

import torch.nn as nn
 

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate all 2 linear layers  
        self.fc1 = nn.Linear(784, 200)
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):
      
        # Use the instantiated layers and return x
        x = self.fc1(x)
        x = self.fc2(x)
        return x

#----------------------------------#

# Conclusion

"""
Cool! You just built your first PyTorch artificial neural network. You are going to build many more during this course.
"""

'\nCool! You just built your first PyTorch artificial neural network. You are going to build many more during this course.\n'