In [1]:
# run this to shorten the data import from the files
import os
path_data = os.path.join(os.path.dirname(os.getcwd()), 'datasets/')


In [2]:
# exercise 01

"""
Convolution operator - OOP way

Let's kick off this chapter by using convolution operator from the torch.nn package. You are going to create a random tensor which will represent your image and random filters to convolve the image with. Then you'll apply those images.

The torch library and the torch.nn package have already been imported for you.
"""

# Instructions

"""

    Create 10 images with shape (1, 28, 28).
    Build 6 convolutional filters of size (3, 3) with stride set to 1 and padding set to 1.
    Apply the filters in the image and print the shape of the feature map.

"""

# solution
import torch
import torch.nn as nn
# Create 10 random images of shape (1, 28, 28)
images = torch.rand(10, 1, 28, 28)

# Build 6 conv. filters
conv_filters = torch.nn.Conv2d(in_channels=1, out_channels=6, kernel_size=3, stride=1, padding=1)

# Convolve the image with the filters 
output_feature = conv_filters(images)
print(output_feature.shape)

#----------------------------------#

# Conclusion

"""
Congratulations! You just made the first step in building CNNs.
"""

torch.Size([10, 6, 28, 28])


'\nCongratulations! You just made the first step in building CNNs.\n'

In [3]:
# exercise 02

"""
Convolution operator - Functional way

While I and most of PyTorch practitioners love the torch.nn package (OOP way), other practitioners prefer building neural network models in a more functional way, using torch.nn.functional. More importantly, it is possible to mix the concepts and use both libraries at the same time (we have already done it in the previous chapter). You are going to build the same neural network you built in the previous exercise, but this time using the functional way.

As before, we have already imported the torch library and torch.nn.functional as F.
"""

# Instructions

"""

    Create 10 random images with shape (1, 28, 28).
    Create 6 random filters with shape (1, 3, 3).
    Convolve the images with the filters.

"""

# solution

import torch.nn.functional as F
# Create 10 random images
image = torch.rand(10, 1, 28, 28)

# Create 6 filters
filters = torch.rand(6, 1, 3, 3)

# Convolve the image with the filters
output_feature = F.conv2d(image, filters, stride=1, padding=1)
print(output_feature.shape)

#----------------------------------#

# Conclusion

"""
Awesome, now you know how to build convolutional layers using functional package.
"""

torch.Size([10, 6, 28, 28])


'\nAwesome, now you know how to build convolutional layers using functional package.\n'

In [4]:
im = torch.tensor([[[[ 8.,  1.,  2.,  5.,  3.,  1.],
          [ 6.,  0.,  0., -5.,  7.,  9.],
          [ 1.,  9., -1., -2.,  2.,  6.],
          [ 0.,  4.,  2., -3.,  4.,  3.],
          [ 2., -1.,  4., -1., -2.,  3.],
          [ 2., -4.,  5.,  9., -7.,  8.]]]])

In [5]:
# exercise 03

"""
Max-pooling operator

Here you are going to practice using max-pooling in both OOP and functional way, and see for yourself that the produced results are the same. We have already created and printed the image for you, and imported torch library in addition to torch.nn and torch.nn.Functional as F packages.
"""

# Instructions

"""

    Build a max-pooling operator with size 2.
    Apply the max-pooling operator in the image (loaded as im).
    Use a max-pooling operator in functional way in the image.
    Print the results of both cases.

"""

# solution

# Build a pooling operator with size `2`.
max_pooling = torch.nn.MaxPool2d(2)

# Apply the pooling operator
output_feature = max_pooling(im)

# Use pooling operator in the image
output_feature_F = F.max_pool2d(im, 2)

# print the results of both cases
print(output_feature)
print(output_feature_F)

#----------------------------------#

# Conclusion

"""
You see how the results are the same. In general, torch.nn and torch.nn.functional are equivalent and the choice for one of them is mostly a personal choice.
"""

tensor([[[[8., 5., 9.],
          [9., 2., 6.],
          [2., 9., 8.]]]])
tensor([[[[8., 5., 9.],
          [9., 2., 6.],
          [2., 9., 8.]]]])


'\nYou see how the results are the same. In general, torch.nn and torch.nn.functional are equivalent and the choice for one of them is mostly a personal choice.\n'

In [6]:
# exercise 04

"""
Average-pooling operator

After coding the max-pooling operator, you are now going to code the average-pooling operator. You just need to replace max-pooling with average pooling.
"""

# Instructions

"""

    Build an average-pooling operator with size 2.
    Apply the average-pooling operator in the image.
    Use an average-pooling operator in functional way in the image, called im.
    Print the results of both cases.

"""

# solution

# Build a pooling operator with size `2`.
avg_pooling = torch.nn.AvgPool2d(2)

# Apply the pooling operator
output_feature = avg_pooling(im)

# Use pooling operator in the image
output_feature_F = F.avg_pool2d(im,2)

# print the results of both cases
print(output_feature)
print(output_feature_F)

#----------------------------------#

# Conclusion

"""
Fantastic job, now you know to apply different types of pooling in addition to convolutions. The moment of truth has arrived, in the lext lecture we are going to learn building convolutional neural networks, the most important technique in the entire field of machine learning.
"""

tensor([[[[ 3.7500,  0.5000,  5.0000],
          [ 3.5000, -1.0000,  3.7500],
          [-0.2500,  4.2500,  0.5000]]]])
tensor([[[[ 3.7500,  0.5000,  5.0000],
          [ 3.5000, -1.0000,  3.7500],
          [-0.2500,  4.2500,  0.5000]]]])


'\nFantastic job, now you know to apply different types of pooling in addition to convolutions. The moment of truth has arrived, in the lext lecture we are going to learn building convolutional neural networks, the most important technique in the entire field of machine learning.\n'

In [7]:
# exercise 05

"""
Your first CNN - __init__ method

You are going to build your first convolutional neural network. You're going to use the MNIST dataset as the dataset, which is made of handwritten digits from 0 to 9. The convolutional neural network is going to have 2 convolutional layers, each followed by a ReLU nonlinearity, and a fully connected layer. We have already imported torch and torch.nn as nn. Remember that each pooling layer halves both the height and the width of the image, so by using 2 pooling layers, the height and width are 1/4 of the original sizes. MNIST images have shape (1, 28, 28)

For the moment, you are going to implement the __init__ method of the net. In the next exercise, you will implement the .forward() method.

NB: We need 2 pooling layers, but we only need to instantiate a pooling layer once, because each pooling layer will have the same configuration. Instead, we will use self.pool twice in the next exercise.
"""

# Instructions

"""

    Instantiate two convolutional filters: the first one should have 5 channels, while the second one should have 10 channels. The kernel_size for both of them should be 3, and both should use padding=1. Use the names of the arguments (instead of using 1, use padding=1).
    Instantiate a ReLU() nonlinearity.
    Instantiate a max pooling layer which halves the size of the image in both directions.
    Instantiate a fully connected layer which connects the units with the number of classes (we are using MNIST, so there are 10 classes).

"""

# solution

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate two convolutional layers
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=5, out_channels=10, kernel_size=3, padding=1)
        
        # Instantiate the ReLU nonlinearity
        self.relu = nn.ReLU()
        
        # Instantiate a max pooling layer
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        
        # Instantiate a fully connected layer
        self.fc = nn.Linear(7*7*10, 10)

#----------------------------------#

# Conclusion

"""
Great job! Now all that remains is implementing the forward() method and you have your first CNN.
"""

'\nGreat job! Now all that remains is implementing the forward() method and you have your first CNN.\n'

In [8]:
# exercise 06

"""
Your first CNN - forward() method

Now that you have declared all the parameters of your CNN, all you need to do is to implement the net's forward() method, and voila, you have your very first PyTorch CNN.

Note: for evaluation purposes, the entire code of the class needs to be in the script. We are using the __init__ method as you have coded it on the previous exercise, while you are going to code the .forward() method here.
"""

# Instructions

"""

    Apply the first convolutional layer, followed by the relu nonlinearity, then in the next line apply max-pooling layer.
    Apply the second convolutional layer, followed by the relu nonlinearity, then in the next line apply max-pooling layer.
    Transform the feature map from 4 dimensional to 2 dimensional space. The first dimension contains the batch size (-1), deduct the second dimension, by multiplying the values for height, width and depth.
    Apply the fully-connected layer and return the result.

"""

# solution

class Net(nn.Module):
    def __init__(self, num_classes):
        super(Net, self).__init__()
		
        # Instantiate the ReLU nonlinearity
        self.relu = nn.ReLU()
        
        # Instantiate two convolutional layers
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=5, out_channels=10, kernel_size=3, padding=1)
        
        # Instantiate a max pooling layer
        self.pool = nn.MaxPool2d(2, 2)
        
        # Instantiate a fully connected layer
        self.fc = nn.Linear(7 * 7 * 10, 10)

    def forward(self, x):

        # Apply conv followd by relu, then in next line pool
        x = self.relu(self.conv1(x))
        x = self.pool(x)

        # Apply conv followd by relu, then in next line pool
        x = self.relu(self.conv2(x))
        x = self.pool(x)

        # Prepare the image for the fully connected layer
        x = x.view(-1, 7*7*10)

        # Apply the fully connected layer and return the result
        return self.fc(x)

#----------------------------------#

# Conclusion

"""
You're awesome (and so is your CNN)! Do the next part to learn how to train it.
"""

"\nYou're awesome (and so is your CNN)! Do the next part to learn how to train it.\n"

In [9]:
import torch
import torchvision
import torch.utils.data
import torchvision.transforms as transforms

transform = transforms.Compose([transforms.ToTensor(),
								transforms.Normalize((0.1307), ((0.3081)))])

trainset = torchvision.datasets.MNIST('/run/media/nero/e753e46e-c457-4237-9670-c71cee45c7bc/Datasets/torchvision/', train=True, 
									  download=True, transform=transform)
testset = torchvision.datasets.MNIST('/run/media/nero/e753e46e-c457-4237-9670-c71cee45c7bc/Datasets/torchvision/', train=False, 
									  download=True, transform=transform)

trainloader = torch.utils.data.DataLoader(trainset, batch_size=32,
                                          shuffle=True, num_workers=4)
testloader = torch.utils.data.DataLoader(testset, batch_size=32,
										 shuffle=False, num_workers=4) 

In [10]:
# exercise 07

"""
Training CNNs

Similarly to what you did in Chapter 2, you are going to train a neural network. This time however, you will train the CNN you built in the previous lesson, instead of a fully connected network. The packages you need have been imported for you and the network (called net) instantiated. The cross-entropy loss function (called criterion) and the Adam optimizer (called optimizer) are also available. We have subsampled the training set so that the training goes faster, and you are going to use a single epoch.
"""

# Instructions

"""

    Compute the predictions from the net.
    Using the predictions and the labels, compute the loss function.
    Compute the gradients for each weight.
    Update the weights using the optimizer.

"""

# solution
import torch.optim as optim

net = Net(num_classes=10)   
optimizer = optim.Adam(net.parameters(), lr=3e-4)
criterion = nn.CrossEntropyLoss()

for i, data in enumerate(trainloader, 0):
    inputs, labels = data
    optimizer.zero_grad()

    # Compute the forward pass
    outputs = net(inputs)
        
    # Compute the loss function
    loss = criterion(outputs, labels)
        
    # Compute the gradients
    loss.backward()
    
    # Update the weights
    optimizer.step()

#----------------------------------#

# Conclusion

"""
Awesome! You now know how to train CNNs! Let's see how accurate it is.
"""

/home/nero/Documents/Estudos/estudos/lib/python3.11/site-packages/torch/autograd/__init__.py:200: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass


"\nAwesome! You now know how to train CNNs! Let's see how accurate it is.\n"

In [11]:
# exercise 08

"""
Using CNNs to make predictions

Building and training neural networks is a very exciting job (trust me, I do it every day)! However, the main utility of neural networks is to make predictions. This is the entire reason why the field of deep learning has bloomed in the last few years, as neural networks predictions are extremely accurate. On this exercise, we are going to use the convolutional neural network you already trained in order to make predictions on the MNIST dataset.

Remember that torch.max() takes two arguments: -output.data - the tensor which contains the data.

    Either 1 to do argmax or 0 to do max.

"""

# Instructions

"""

    Iterate over the given test_loader, saving the results of each iteration in data.
    Get the image and label from the data tuple, storing the results in image and label.
    Make a forward pass in the net using your image.
    Get the net prediction using torch.max() function.

"""

# solution

# Iterate over the data in the test_loader
for i, data in enumerate(testloader):
  
    # Get the image and label from data
    image, label = data
    
    # Make a forward pass in the net with your image
    output = net(image)
    
    # Argmax the results of the net
    _, predicted = torch.max(output.data, 1)
    if torch.equal(predicted, label):
        print("Yipes, your net made the right prediction " + str(predicted))
    else:
        print("Your net prediction was " + str(predicted) + ", but the correct label is: " + str(label))

#----------------------------------#

# Conclusion

"""
Good job! Is your CNN accurate enough?
"""

Your net prediction was tensor([7, 2, 1, 0, 4, 1, 4, 9, 6, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6, 5,
        4, 0, 7, 4, 0, 1, 3, 1]), but the correct label is: tensor([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6, 5,
        4, 0, 7, 4, 0, 1, 3, 1])
Your net prediction was tensor([3, 0, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2, 3, 5, 1, 2, 4, 4, 6, 3, 5, 5, 6, 0,
        4, 1, 9, 5, 7, 8, 9, 2]), but the correct label is: tensor([3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2, 3, 5, 1, 2, 4, 4, 6, 3, 5, 5, 6, 0,
        4, 1, 9, 5, 7, 8, 9, 3])
Your net prediction was tensor([7, 4, 6, 4, 3, 0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3,
        6, 1, 3, 6, 4, 3, 1, 4]), but the correct label is: tensor([7, 4, 6, 4, 3, 0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3,
        6, 1, 3, 6, 9, 3, 1, 4])
Yipes, your net made the right prediction tensor([1, 7, 6, 9, 6, 0, 5, 4, 9, 9, 2, 1, 9, 4, 8, 7, 3, 9, 7, 4, 4, 4, 9, 2,
        5, 4, 7, 6, 7, 9, 0, 5])
Yipes, your ne

'\nGood job! Is your CNN accurate enough?\n'

In [12]:
# Evaluation

# solution
total = 0
correct = 0

# Set the model in eval mode
net.eval()

for i, data in enumerate(testloader, 0):
    inputs, labels = data

    
    # Do the forward pass and get the predictions
    outputs = net(inputs)
    _, outputs = torch.max(outputs.data, 1)
    total += labels.size(0)
    correct += (outputs == labels).sum().item()
print('The testing set accuracy of the network is: %d %%' % (100 * correct / total))

The testing set accuracy of the network is: 93 %
