In [1]:
# run this to shorten the data import from the files
import os
cwd = os.path.dirname(os.getcwd())+'/'
path_data = os.path.join(os.path.dirname(os.getcwd()), 'datasets/')


In [2]:
# exercise 01

"""
Text generation examples

In this exercise, you are going to experiment on two pre-trained models for text generation.

The first model will generate one phrase based on the character Sheldon of The Big Bang Theory TV show, and the second model will generate a Shakespeare poems up to 400 characters.

The models are loaded on the sheldon_model and poem_model variables. Also, two custom functions to help generate text are available: generate_sheldon_phrase() and generate_poem(). Both receive the pre-trained model and a context string as parameters.
"""

# Instructions

"""

    Use pre-defined function generate_sheldon_phrase() with parameters sheldon_model and sheldon_context and store the output in the sheldon_phrase variable.
    Print the obtained phrase.
    Store the given text into the poem_context variable.
    Print the poem generated by applying the function generate_poem() with the poem_model and poem_context parameters.

"""

# solution

"""# Context for Sheldon phrase
sheldon_context = "I’m not insane, my mother had me tested. "

# Generate one Sheldon phrase
sheldon_phrase = generate_sheldon_phrase(sheldon_model, sheldon_context)

# Print the phrase
print(sheldon_phrase)

# Context for poem
poem_context = "May thy beauty forever remain"

# Print the poem
print(generate_poem(poem_model, poem_context))"""

#----------------------------------#

print('''<script.py> output:
    i’m not insane, my mother had me tested. ove to the back of the sent of the fall of my resent of the way of the find that i can have to the locken and i was a sense to the little of the contric of the start of the child be the look and the s
    
    
    Your poem lies below: 
    
    
    May thy beauty forever remain,
    without thy love, and me at self i wast now.
    
    
    
    shen make the wail, and then i hase no love,
    be the was my sare and the world, or my heart thee thee,
    rone the beauty my then have dore me song,
    and from the will of a lover of self and deet,
    ''')

# Conclusion

"""
Really nice, right? There are many possible applications to text generation, and by using characters as tokens you can create good models with less data, meaning that with tens of thousands of example sentences you can create a model that has interesting results. In this first model, you can see that the generated phrase does not make any sense. Don't worry, the trained model used very few data and was trained for just 10 epochs. By using more data (sentence examples) and training longer, you can achieve much better results.
"""

<script.py> output:
    i’m not insane, my mother had me tested. ove to the back of the sent of the fall of my resent of the way of the find that i can have to the locken and i was a sense to the little of the contric of the start of the child be the look and the s
    
    
    Your poem lies below: 
    
    
    May thy beauty forever remain,
    without thy love, and me at self i wast now.
    
    
    
    shen make the wail, and then i hase no love,
    be the was my sare and the world, or my heart thee thee,
    rone the beauty my then have dore me song,
    and from the will of a lover of self and deet,
    


"\nReally nice, right? There are many possible applications to text generation, and by using characters as tokens you can create good models with less data, meaning that with tens of thousands of example sentences you can create a model that has interesting results. In this first model, you can see that the generated phrase does not make any sense. Don't worry, the trained model used very few data and was trained for just 10 epochs. By using more data (sentence examples) and training longer, you can achieve much better results.\n"

In [ ]:
pt_length = 8

def encode_sequences(lines, tokenizer=pt_tokenizer, length=pt_length):
    """Use the tokenizer to encode the given texts
    
    Transform the given texts into an numpy array of index sequences padded to length `length`.

    Args:
        lines (list or numpy.array): The given texts.
        tokenizer (keras.preprocessing.text.Tokenizer): The fitted tokenizer object. Defaults to the trained Portuguese tokenizer.
        length (int): The length to pad the sequences. Defaults to the maximum length of the Portuguese sentences (8).

    Returns:
        The padded numpy.array of indices sequences.
    
    """
    
    # integer encode sequences
    X = tokenizer.texts_to_sequences(lines)
    # pad sequences with 0 values
    X = pad_sequences(X, maxlen=length, padding='post')
    return X

In [ ]:
def translate_many(model, sentences):
    """ Translate a list of sentences

    Use the pre-trained model to loop over the sentences and translate one by one.

    Args:
        model (keras.models.Sequential): The pre-trained NMT model.
        sentences (list or numpy.array): The list of sentences to translate.
    
    Returns:
        A list containing the translated sentences.
    
    """
    translated = []
    for i, sentence in enumerate(sentences):
        # translate encoded sentence text
        translation = predict_one(model, sentence)
        translated.append(translation)
    
    return translated

In [ ]:
def predict_one(model, source, ix_to_word=index_to_word):
    source = source.reshape((1, source.shape[0]))
    prediction = model.predict(source, verbose=0)[0]
    integers = [np.argmax(vector) for vector in prediction]
    target = list()
    for i in integers:
        word = ix_to_word.get(i, None)
        if word is None:
            break
        target.append(word)
    return ' '.join(target)

In [3]:
# exercise 02

"""
NMT example

This exercise aims to build on the sneak peek you got of NMT at the beginning of the course. You will continue to translate Portuguese small phrases into English.

Some sample sentences are available on the sentences variable and are printed on the console.

Also, a pre-trained model is available on the model variable and you will use two custom functions to simplify some steps:

    encode_sequences(): Change texts into sequence of numerical indexes and pad them.
    translate_many(): Uses the pre-trained model to translate a list of sentences from Portuguese into English. Later you will code this function yourself.

For more details on the functions, use help(). The package pandas is loaded as pd.
"""

# Instructions

"""

    Use the encode_sequences() function to pre-process the texts and save the results in the X variable.
    Translate the sentences using the translate_many() function by passing X as a parameter.
    Create a pd.DataFrame() with the original and translated lists as columns.
    Print the data frame.

"""

# solution

"""# Transform text into sequence of indexes and pad
X = encode_sequences(sentences)

# Print the sequences of indexes
print(X)

# Translate the sentences
translated = translate_many(model, X)

# Create pandas DataFrame with original and translated
df = pd.DataFrame({'Original': sentences, 'Translated': translated})

# Print the DataFrame
print(df)"""


print("""[[ 452    0    0    0    0    0    0    0]
 [  23  224   68    0    0    0    0    0]
 [1374    0    0    0    0    0    0    0]
 [   1  302   31    9    0    0    0    0]
 [   2    6   31   63    0    0    0    0]
 [   2    6  155    0    0    0    0    0]
 [  35 2134    0    0    0    0    0    0]
 [   1 1525    0    0    0    0    0    0]
 [   5 1142    0    0    0    0    0    0]
 [ 578   44    0    0    0    0    0    0]]
              Original     Translated
0             obrigada      thank you
1    vocês podem ficar   you may stay
2               ataque         attack
3  eu acredito em você  i believe you
4     tom está em casa    tom is home
5     tom está sozinho   tom is alone
6        posso sentila  i can feel it
7            eu dancei       i danced
8     estou contratado         im wet
9     experimenta isto       try this""")

#----------------------------------#

# Conclusion

"""
Cool, isn't it? Most of the translated sentences are correct, but some are wrong like 'estou contratado' does not mean 'im drunk', instead it means 'im hired. By increasing the number of examples (only 5,000 were used on the pre-trained model), and training for more epochs you could achieve a better result.
"""

[[ 452    0    0    0    0    0    0    0]
 [  23  224   68    0    0    0    0    0]
 [1374    0    0    0    0    0    0    0]
 [   1  302   31    9    0    0    0    0]
 [   2    6   31   63    0    0    0    0]
 [   2    6  155    0    0    0    0    0]
 [  35 2134    0    0    0    0    0    0]
 [   1 1525    0    0    0    0    0    0]
 [   5 1142    0    0    0    0    0    0]
 [ 578   44    0    0    0    0    0    0]]
              Original     Translated
0             obrigada      thank you
1    vocês podem ficar   you may stay
2               ataque         attack
3  eu acredito em você  i believe you
4     tom está em casa    tom is home
5     tom está sozinho   tom is alone
6        posso sentila  i can feel it
7            eu dancei       i danced
8     estou contratado         im wet
9     experimenta isto       try this


"\nCool, isn't it? Most of the translated sentences are correct, but some are wrong like 'estou contratado' does not mean 'im drunk', instead it means 'im hired. By increasing the number of examples (only 5,000 were used on the pre-trained model), and training for more epochs you could achieve a better result.\n"

In [2]:
# exercise 03

"""
Predict next character

In this exercise, you will code the function to predict the next character given a trained model. You will use the past 20 chars to predict the next one. You will learn how to train the model in the next lesson, as this step is integral before model training.

This is the initial step to create rules for generating sentences, paragraphs, short texts or other blocks of text as needed.

The variables n_vocab, chars_window and the dictionary index_to_char are already loaded in the environment. Also, the functions below are already created for you:

    initialize_X(): Transforms the text input into a sequence of index numbers with the correct shape.
    predict_next_char(): Gets the next character using the .predict() method of the model class and the index_to_char dictionary.

"""

# Instructions

"""

    Define the function get_next_char() and add the parameters initial_text and chars_window without default values.
    Use initialize_X() function and pass variable char_to_index to obtain a vector of zeros to be used for prediction.
    Use the predict_next_char() function to obtain the prediction and store it in the next_char variable.
    Print the predicted character by applying the defined function on the given initial_text.

"""

# solution

def get_next_char(model, initial_text, chars_window, char_to_index, index_to_char):
  	# Initialize the X vector with zeros
    X = initialize_X(initial_text, chars_window, char_to_index)
    
    # Get next character using the model
    next_char = predict_next_char(model, X, index_to_char)
	
    return next_char

# Define context sentence and print the generated text
initial_text = "I am not insane, "
print("Next character: {0}".format(get_next_char(model, initial_text, 20, char_to_index, index_to_char)))

#----------------------------------#

# Conclusion

"""
This function can help you to obtain one next character using the model. It used the previous 20 chars to make the prediction, and depending on the application you have, you may use higher or lower values. Seeing just this predicted character doesn't make much sense, that is why you will see next how to generate a full sentence.
"""

'\n\n'

In [3]:
# exercise 04

"""
Generate sentence with context

In this exercise, you are going to experiment on a pre-trained model for text generation. The model is already loaded in the environment in the model variable, as well as the initialize_params() and get_next_token() functions.

This later uses the pre-trained model to predict the next character and return three variables: the next character next_char, the updated sentence res and the the shifted text seq that will be used to predict the next one.

You will define a function that receives a pre-trained model and a string that will be the start of the generated sentence as inputs. This is a good practice to generate text with context. The sentence limit of 100 characters is an example, you can use other limits (or even without limit) in your applications.
"""

# Instructions

"""

    Pass the initial_text variable to the initialize_params() function.
    Create conditions to stop the loop when the counter reaches 100 or a dot (r'.') is found.
    Pass the initial values res, seq to the get_next_token() function to obtain the next char.
    Print the example phrase generated by the defined function.

"""

# solution

def generate_phrase(model, initial_text):
    # Initialize variables  
    res, seq, counter, next_char = initialize_params(initial_text)
    
    # Loop until stop conditions are met
    while counter < 100 and next_char != r'.':
      	# Get next char using the model and append to the sentence
        next_char, res, seq = get_next_token(model, res, seq)
        # Update the counter
        counter = counter + 1
    return res
  
# Create a phrase
print(generate_phrase(model, "I am not insane, "))

#----------------------------------#

# Conclusion

"""
Cool! You can see that the generated text belongs to the Big Bang Theory universe. That is because the model was trained using phrases by the character Sheldon. Depending on trained data, the model will generate different phrases. You can try with other standard examples such as Sheakespeare collection to generate poems, or maybe on other famous authors from the literature. You choose! Note that the model was trained with 100 epochs and used only 20 characters to predict the next one. By incresing the chars_window and training for more epochs, you can obtain better predictions.
"""

'\n\n'

In [4]:
# exercise 05

"""
Change the probability scale

In this exercise, you will see the difference in the resulted sentence when using different values of temperature to scale the probability distribution.

The function generate_phrase() is an adaptation of the function you created before and is already loaded in the environment. It receives the parameters model with the pre-trained model, initial_text with the context text and temperature that is the value to scale the softmax() function.
"""

# Instructions

"""

    Store the list of temperatures to the temperatures variable.
    Loop a variable temperature over the temperatures list.
    Generate a phrase using the pre-loaded function generate_phrase().
    Print the temperature and the generated sentence.

"""

# solution

"""# Define the initial text
initial_text = "Spock and me "

# Define a vector with temperature values
temperatures = [0.2, 0.8, 1.0, 3.0, 10.0]

# Loop over temperatures and generate phrases
for temperature in temperatures:
	# Generate a phrase
	phrase = generate_phrase(model, initial_text, temperature)
    
	# Print the phrase
	print('Temperature {0}: {1}'.format(temperature, phrase))"""

print("""    Temperature 0.2: spock and me and the big back of the little of the start of the same of the beat of the start.
    Temperature 0.8: spock and me with his ravites of my number of to be movies that.
    Temperature 1.0: spock and me in my body.
    Temperature 3.0: spock and me zksum.
    Temperature 10.0: spock and me .""")

#----------------------------------#

# Conclusion

"""
You can see that when the temperature is high, the text start to make less sense. If the model was trained with a larger sample and for more epochs, you would get better phrases. Also, when temperature is low, the phrases seems more realistic.
"""

    Temperature 0.2: spock and me and the big back of the little of the start of the same of the beat of the start.
    Temperature 0.8: spock and me with his ravites of my number of to be movies that.
    Temperature 1.0: spock and me in my body.
    Temperature 3.0: spock and me zksum.
    Temperature 10.0: spock and me .


'\nYou can see that when the temperature is high, the text start to make less sense. If the model was trained with a larger sample and for more epochs, you would get better phrases. Also, when temperature is low, the phrases seems more realistic.\n'

In [7]:
import pandas as pd

with open(path_data+'sheldon.txt', 'r') as file:
    sheldon = file.read()
    file.close()

sheldon[:50]

'so if a photon is directed through a plane with tw'

In [8]:
# exercise 06

"""
Create vectors of sentences and next characters

This exercise aims to emphasize more the value of data preparation. You will use texts containing phrases of the character Sheldon from The Big Bang Theory TV show as input and will create vectors of sentence indexes and next characters that are needed before creating a text generation model.

The text is available in the sheldon variable, as well as the vocabulary (characters) on the vocabulary variable and the hyperparameters chars_window and step defined with values 20 and 3. This means that a sequence of 20 characters will be used to predict the next one, and the window will shift 3 characters on every iteration.

Also, the package pandas as pd is loaded in the environment.
"""

# Instructions

"""

    Split the text by line break to loop through sentences.
    Loop until the end of the sentence minus chars_window.
    Append the portion of the sentence that has chars_window characters to the sentences variable and append the next character to the next_chars variable.
    Use the obtained vectors to create a pd.DataFrame() and print its first rows.

"""

# solution

chars_window = 20
step = 3

# Instantiate the vectors
sentences = []
next_chars = []
# Loop for every sentence
for sentence in sheldon.split('\n'):
    # Get 20 previous chars and next char; then shift by step
    for i in range(0, len(sentence) - chars_window, step):
        sentences.append(sentence[i:i + chars_window])
        next_chars.append(sentence[i + chars_window])

# Define a Data Frame with the vectors
df = pd.DataFrame({'sentence': sentences, 'next_char': next_chars})

# Print the initial rows
print(df.head())

#----------------------------------#

# Conclusion

"""
You can see that the texts were shifted by 3 characters on every step to create examples of sentences and next characters. These vectors will later be processed to contain only index numbers instead of strings, and then can be used to train a supervised RNN model that learns to replicate sentences in the universe the texts belongs to. Here, characters were used as tokens, but if you have enough data you can also create a model to predict the next word.
"""

               sentence next_char
0  so if a photon is di         r
1  if a photon is direc         t
2  a photon is directed          
3  hoton is directed th         r
4  on is directed throu         g


'\nYou can see that the texts were shifted by 3 characters on every step to create examples of sentences and next characters. These vectors will later be processed to contain only index numbers instead of strings, and then can be used to train a supervised RNN model that learns to replicate sentences in the universe the texts belongs to. Here, characters were used as tokens, but if you have enough data you can also create a model to predict the next word.\n'

In [38]:
char_to_index = {' ': 0, '!': 1, '$': 2, '%': 3, '&': 4, '(': 5, ')': 6, ',': 7, '-': 8, '.': 9, '/': 10, '0': 11, '1': 12, '2': 13, '3': 14, '4': 15, '5': 16, '6': 17, '7': 18, '8': 19, '9': 20, ';': 21, '<': 22, '=': 23, '>': 24, '?': 25, 'a': 26, 'b': 27, 'c': 28, 'd': 29, 'e': 30, 'f': 31, 'g': 32, 'h': 33, 'i': 34, 'j': 35, 'k': 36, 'l': 37, 'm': 38, 'n': 39, 'o': 40, 'p': 41, 'q': 42, 'r': 43, 's': 44, 't': 45, 'u': 46, 'v': 47, 'w': 48, 'x': 49, 'y': 50, 'z': 51, '}': 52, '¿': 53, 'à': 54, 'á': 55, 'è': 56, 'é': 57, 'ê': 58, 'ñ': 59, 'ó': 60, 'ö': 61, 'ü': 62, '–': 63, '‘': 64, '’': 65, '“': 66, '”': 67, '…': 68}

In [47]:
def create_enumerated_dictionary(text):
    # Create a set of all the unique characters in the text
    unique_characters = set(text)

    # Create an enumerated dictionary for each unique character
    enumerated_dictionary = {}
    for i, character in enumerate(unique_characters):
        enumerated_dictionary[character] = i

    return enumerated_dictionary


In [48]:
char_to_index = create_enumerated_dictionary(sheldon)
char_to_index

{'9': 0,
 'ê': 1,
 'à': 2,
 'f': 3,
 '–': 4,
 ',': 5,
 'u': 6,
 '5': 7,
 ';': 8,
 '¿': 9,
 ')': 10,
 'd': 11,
 '.': 12,
 '%': 13,
 'ñ': 14,
 '7': 15,
 '8': 16,
 '’': 17,
 'e': 18,
 '?': 19,
 'ü': 20,
 'g': 21,
 'n': 22,
 'x': 23,
 'w': 24,
 '<': 25,
 '\n': 26,
 '(': 27,
 'i': 28,
 '…': 29,
 'ö': 30,
 'q': 31,
 'l': 32,
 '0': 33,
 '$': 34,
 ' ': 35,
 '>': 36,
 '‘': 37,
 'á': 38,
 'z': 39,
 '“': 40,
 'é': 41,
 'r': 42,
 '&': 43,
 '2': 44,
 'b': 45,
 'v': 46,
 's': 47,
 '/': 48,
 '\\': 49,
 'm': 50,
 'c': 51,
 't': 52,
 'k': 53,
 '4': 54,
 '3': 55,
 '-': 56,
 'a': 57,
 '6': 58,
 '}': 59,
 'o': 60,
 '=': 61,
 'è': 62,
 '1': 63,
 'j': 64,
 '!': 65,
 'h': 66,
 'y': 67,
 'p': 68,
 '”': 69,
 'ó': 70}

In [55]:
# exercise 07

"""
Preparing the data for training

In this exercise, you will continue to prepare the data to train the model. After creating the arrays of sentences and next characters, you need to transform them to numerical values that can be used on the model.

This step is necessary because the RNN models expect numbers only and not strings. You will create numerical arrays that have zeros or ones in the positions representing the characters present on the sentences. Ones (or True) represent the corresponding character is present, while zeros (or False) represent the absence of the character in that position of the sentence.

The variables sentences, next_char, n_vocab, chars_window, num_seqs (number of sentences in the training data) are already loaded in the environment, as well as numpy as np.
"""

# Instructions

"""

    Instantiate a np.array() with zeros and shape (number of sentences, characters window, vocabulary size).
    Use the dictionary char_to_index to set the position of the current char to 1.
    Set the current next character to 1.
    Print the first position of each array.

"""

# solution

import numpy as np

num_seqs, chars_window, n_vocab = len(sentences), 20, len(char_to_index)

sentences = [sentence.replace('\\', '') for sentence in sentences]

# Instantiate the variables with zeros
numerical_sentences = np.zeros((num_seqs, chars_window, n_vocab), dtype=bool)
numerical_next_chars = np.zeros((num_seqs, n_vocab), dtype=bool)

# Loop for every sentence
for i, sentence in enumerate(sentences):
  # Loop for every character in sentence
  for t, char in enumerate(sentence):
    # Set position of the character to 1
    numerical_sentences[i, t, char_to_index[char]] = 1

    # Set next character to 1
    numerical_next_chars[i, char_to_index[next_chars[i]]] = 1

# Print the first position of each
print(numerical_sentences[0], numerical_next_chars[0], sep="\n")

#----------------------------------#

# Conclusion

"""
That's it! With the variables numerical_sentences and numerical_next_chars you are ready to train text generation models.
"""

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False]


"\nThat's it! With the variables numerical_sentences and numerical_next_chars you are ready to train text generation models.\n"

In [57]:
# exercise 08

"""
Creating the text generation model

In this exercise, you will define a text generation model using Keras.

The variables n_vocab containing the vocabulary size and input_shape containing the shape of the data used for training are already loaded in the environment. Also, the weights of a pre-trained model is available on file model_weights.h5. The model was trained with 40 epochs on the training data. Recap that to train a model in Keras, you just use the method .fit() on the training data (X, y), and the parameter epochs. For example:

model.fit(X_train, y_train, epochs=40)

"""

# Instructions

"""

    Add one LSTM layer returning the sequences.
    Add one LSTM layer not returning the sequences.
    Add the output layer with n_vocab units.
    Display the model summary.

"""

# solution

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

input_shape = (chars_window, n_vocab)

# Instantiate the model
model = Sequential(name="LSTM model")

# Add two LSTM layers
model.add(LSTM(64, input_shape=input_shape, dropout=0.15, recurrent_dropout=0.15, return_sequences=True, name="Input_layer"))
model.add(LSTM(64, dropout=0.15, recurrent_dropout=0.15, return_sequences=False, name="LSTM_hidden"))

# Add the output layer
model.add(Dense(n_vocab, activation='softmax', name="Output_layer"))

# Compile and load weights
model.compile(loss='categorical_crossentropy', optimizer='adam')
#model.load_weights('model_weights.h5')
# Summary
model.summary()

#----------------------------------#

# Conclusion

"""
The main point of the text generation model is that it uses the whole vocabulary as classes on the output layer. This means that if the vocabulary is big (hundred of thousands), then the required amount of data is also very big.
"""

Model: "LSTM model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Input_layer (LSTM)          (None, 20, 64)            34816     
                                                                 
 LSTM_hidden (LSTM)          (None, 64)                33024     
                                                                 
 Output_layer (Dense)        (None, 71)                4615      
                                                                 
Total params: 72455 (283.03 KB)
Trainable params: 72455 (283.03 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


'\nThe main point of the text generation model is that it uses the whole vocabulary as classes on the output layer. This means that if the vocabulary is big (hundred of thousands), then the required amount of data is also very big.\n'

In [8]:
# exercise 09

"""
Preparing the input text

You have seen in the video how to prepare the input and output texts. This exercise aims to show a common practice that is to use the maximum length of the sentences to pad all of them, this way no information will be lost.

Since the RNN models need the inputs to have the same size, this is a way to pad all sentences and just add zeros to the smaller sentences, without cutting the larger ones.

Also, you will use words instead of characters to represent the tokens, this is a common approach for NMT models.

The Portuguese texts are loaded on the pt_sentences variable and a fitted tokenizer on the input_tokenizer variable.
"""

# Instructions

"""

    Use the .split() method on each sentence to split by white space and obtain the number of words in the sentence.
    Use the .texts_to_sequences() method to transform text into sequence of indexes.
    Use the obtained maximum length of sentences to pad them.
    Print the first transformed sentence.

"""

# solution

# Get maximum length of the sentences
pt_length = max([len(sentence.split()) for sentence in pt_sentences])

# Transform text to sequence of numerical indexes
X = input_tokenizer.texts_to_sequences(pt_sentences)

# Pad the sequences
X = pad_sequences(X, maxlen=pt_length, padding='post')

# Print first sentence
print(pt_sentences[0])

# Print transformed sentence
print(X[0])

#----------------------------------#

# Conclusion

"""
Perfect! You can see that the input language now has sequences of indexes, and when the sentence is smaller than the maximum length, there are zeros in the right positions of the sentence. No sentence lost any information due to padding.
"""

'\n\n'

In [9]:
# exercise 10

"""
Preparing the output text

In this exercise, you will prepare the output texts to be used on the translation model. Apart from transforming the text to sequences of indexes, you also need to one-hot encode each index.

The English texts are loaded on the en_sentences variable, the fitted tokenizer on the output_tokenizer variable and the English vocabulary size on en_vocab_size.

Also, a function to perform the first steps of transforming the output language (transformation of texts into sequence of indexes) is already created. The function is loaded on the environment as transform_text_to_sequences() and has two parameters: sentences that expect a list of sentences in English and tokenizer that expects a fitted Tokenizer object from the keras.preprocessing.text module.

numpy is loaded as np.
"""

# Instructions

"""

    Pass the en_sentences and output_tokenizer variables to the transform_text_to_sequences() function to initialize the Y variable.
    Use the to_categorical() function to one-hot encode the sentences. Use the en_vocab_size variable as number of classes.
    Transform the temporary list to numpy array and reshape to have shape equal to (num_sentences, sentences_len, en_vocab_size).
    Print the raw text and the transformed one.

"""

# solution

# Initialize the variable
Y = transform_text_to_sequences(en_sentences, output_tokenizer)

# Temporary list
ylist = list()
for sequence in Y:
  	# One-hot encode sentence and append to list
    ylist.append(to_categorical(sequence, num_classes=en_vocab_size))

# Update the variable
Y = np.array(ylist).reshape(Y.shape[0], Y.shape[1], en_vocab_size)

# Print the raw sentence and its transformed version
print("Raw sentence: {0}\nTransformed: {1}".format(en_sentences[0], Y[0]))

#----------------------------------#

# Conclusion

"""
Impressive. Now you are able to transform input and otput languages to the correct format to be used on a Neural Machine Translation model. Also, don't bother that all the printed numbers from the tranformed text seems to be all zeros, they are not! Since the vocabulary size is 1269, the 1's didn't appear on the output but they are somewhere in the middle of all those zeros. Now, are you ready to create a NMT model?
"""

'\n\n'

In [ ]:
# exercise 11

"""
Translate Portuguese to English

This is the last exercise of the course, congratulations on getting here!

You will learn how to use NMT models for making translations.

A model that encodes Portuguese small phrases and decodes them into English small phrases was pre-trained and is loaded in the model variable.

Also, the function predict_one() is already loaded, use help() for details and the dataset is available on the test (raw text) and X_test (tokenized) variables.

You will define a function to translate a list of sentences. In the parameters, sentences is a list of phrases to be translated, index_to_word is a dict containing numerical indexes as keys and words as values for the English language, loaded in the en_index_to_word variable.

The model summary has been printed for your consideration.
"""

# Instructions

"""

    Loop over the enumerated iterator of the phrases.
    Use the pre-loaded function predict_one() to translate one phrase.
    Print the translation result.
    Call the defined function to translate the initial 10 phrases of the X_test variable.

"""

# solution

# Function to predict many phrases
def predict_many(model, sentences, index_to_word, raw_dataset):
    for i, sentence in enumerate(sentences):
        # Translate the Portuguese sentence
        translation = predict_one(model, sentence, index_to_word)
        
        # Get the raw Portuguese and English sentences
        raw_target, raw_src = raw_dataset[i]
        
        # Print the correct Portuguese and English sentences and the predicted
        print('src=[%s], target=[%s], predicted=[%s]' % (raw_src, raw_target, translation))

predict_many(model, X_test[:10], en_index_to_word, test)

#----------------------------------#

# Conclusion

"""
Great! This translation model was trained in fairly small sentences (up to 8 words). The longer the sentence to translate gets, more complex the model need to be.
"""