In [1]:
# run this to shorten the data import from the files
path_data = '/home/nero/Documents/Estudos/DataCamp/Python/courses/Designing_Machine_Learning_Workflows_in_Python/datasets/'
import pandas as pd
import numpy as np


In [2]:
# exercise 01

"""
A simple outlier

When you first encounter a new type of algorithm, it is always a great idea to test it with a very simple example. So you decide to create a list containing thirty examples with the value 1.0 and just one example with value 10.0, which you expect should be flagged as an outlier. To make sure you use the algorithm correctly, you convert the list to a pandas dataframe, and feed it into the local outlier factor algorithm. pandas is available to you as pd.
"""

# Instructions

"""

    Import the LocalOutlierFactor module as lof for convenience.
    Create a list with thirty 1s followed by a 10, [1.0, 1.0, ..., 1.0, 10.0].
    Cast the list to a data frame.
    Print the outlier scores produced by the local outlier factor algorithm.

"""

# solution

# Import the LocalOutlierFactor module
from sklearn.neighbors import LocalOutlierFactor as lof

# Create the list [1.0, 1.0, ..., 1.0, 10.0] as explained
x = [1.0]*30
x.append(10)

# Cast to a data frame
X = pd.DataFrame(x)

# Fit the local outlier factor and print the outlier scores
print(lof().fit_predict(X))

#----------------------------------#

# Conclusion

"""
Great, this worked as expected. The algorithm correctly identified the 10.0 as an outlier since it labeled it -1 which stands for anomalous. Let's move on.
"""

[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1 -1]


"\nGreat, this worked as expected. The algorithm correctly identified the 10.0 as an outlier since it labeled it -1 which stands for anomalous. Let's move on.\n"

In [20]:
arrh = pd.read_csv(path_data+'arrh.csv')

'''for column in arrh.columns:
    # Replace negative values with 0
    arrh[column] = arrh[column].apply(lambda x: max(x, 0))'''

X = arrh.drop('class', axis=1)
ground_truth = arrh['class']

In [10]:
ground_truth.value_counts()

class
1    245
0    207
Name: count, dtype: int64

In [13]:
# exercise 02

"""
LoF contamination

Your medical advisor at the arrhythmia startup informs you that your training data might not contain all possible types of arrhythmia. How on earth will you detect these other types without any labeled examples? Could an anomaly detector tell the difference between healthy and unhealthy without access to labels? But first, you experiment with the contamination parameter to see its effect on the confusion matrix. You have LocalOutlierFactor as lof, numpy as np, the labels as ground_truth encoded in -1and 1 just like local outlier factor output, and the unlabeled training data as X.
"""

# Instructions

"""
Fit a local outlier factor and output the predictions on X and print the confusion matrix for these predictions.
---
Repeat but now set the proportion of datapoints to be flagged as outliers to 0.2. Print the confusion matrix.
---
Now set the contamination to be equal to the actual proportion of outliers in the data.
"""

# solution
from sklearn.metrics import confusion_matrix
# Fit the local outlier factor and output predictions
preds = lof().fit_predict(X)

# Print the confusion matrix
print(confusion_matrix(ground_truth, preds))

#----------------------------------#

# Set the contamination parameter to 0.2
preds = lof(contamination=0.2).fit_predict(X)

# Print the confusion matrix
print(confusion_matrix(ground_truth, preds))

#----------------------------------#

# Contamination to match outlier frequency in ground_truth
preds = lof(
  contamination=round(np.mean(ground_truth == True),1)).fit_predict(X)

# Print the confusion matrix
print(confusion_matrix(ground_truth, preds))

#----------------------------------#

# Conclusion

"""
You now have much more control over the local outlier factor algorithm.
"""

[[  0   0   0]
 [ 31   0 176]
 [  2   0 243]]
[[  0   0   0]
 [ 72   0 135]
 [ 19   0 226]]
[[  0   0   0]
 [149   0  58]
 [ 77   0 168]]


'\nYou now have much more control over the local outlier factor algorithm.\n'

In [15]:
# exercise 03

"""
A simple novelty

You find novelty detection more useful than outlier detection, but want to make sure it works on the simple example you came up with before. This time you will use a sequence of thirty examples all with value 1.0 as a training set, and try to see if the example 10.0 is labeled as a novelty. You have access to pandas as pd, and the LocalOutlierFactor module as lof.
"""

# Instructions

"""

    Create a pandas DataFrame containing thirty examples all equal to 1.0.
    Initialize a local outlier factor novelty detector.
    Fit the detector to the training data.
    Output the novelty label of the datapoint 10.0, casted to a DataFrame.

"""

# solution

# Create a list of thirty 1s and cast to a dataframe
X = pd.DataFrame([1.0]*30)

# Create an instance of a lof novelty detector
detector = lof(novelty=True)

# Fit the detector to the data
detector.fit(X)

# Use it to predict the label of an example with value 10.0
print(detector.predict(pd.DataFrame([10])))

#----------------------------------#

# Conclusion

"""
Great, you are now reassured that you understand the method correctly: 10.0 is labelled as -1, which means it is considered novel.
"""

[-1]


'\nGreat, you are now reassured that you understand the method correctly: 10.0 is labelled as -1, which means it is considered novel.\n'

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, ground_truth, test_size=0.25, random_state=42)

In [22]:
# exercise 04

"""
Three novelty detectors

Finally, you know enough to run some tests on the use of a few anomaly detectors on the arrhythmia dataset. To test their performance, you will train them on an unlabeled training dataset, but then compare their predictions to the ground truth on the test data using their method .score_samples(). This time, you will be asked to import the detectors as part of the exercise, but you do have the data X_train, X_test, y_train, y_test preloaded as usual.
"""

# Instructions

"""

    Import the one-class SVM detector from the svm module as onesvm, fit it to the training data, and score the test data.
---
    Adapt your code to import the isolation forest from the ensemble module as isof, fit it and score the test data.
---
    Adapt your code to import the LocalOutlierFactor module as lof, fit it to the training data, and score the test data.

"""

# solution

# Import the novelty detector
from sklearn.svm import OneClassSVM as onesvm

# Fit it to the training data and score the test data
svm_detector = onesvm().fit(X_train)
scores = svm_detector.score_samples(X_test)

#----------------------------------#

# Import the novelty detector
from sklearn.ensemble import IsolationForest as isof

# Fit it to the training data and score the test data
isof_detector = isof().fit(X_train)
isof_scores = isof_detector.score_samples(X_test)

#----------------------------------#

# Import the novelty detector
from sklearn.neighbors import LocalOutlierFactor as lof

# Fit it to the training data and score the test data
lof_detector = lof(novelty=True).fit(X_train)
lof_scores = lof_detector.score_samples(X_test)

#----------------------------------#

# Conclusion

"""
Wonderful, you now have a broad selection of detectors to choose from.
"""

/home/nero/Documents/Estudos/estudos/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LocalOutlierFactor was fitted with feature names
  warnings.warn(


'\nWonderful, you now have a broad selection of detectors to choose from.\n'

In [23]:
# exercise 05

"""
Contamination revisited

You notice that one-class SVM does not have a contamination parameter. But you know well by now that you really need a way to control the proportion of examples that are labeled as novelties in order to control your false positive rate. So you decide to experiment with thresholding the scores. The detector has been imported as onesvm, you also have available the data as X_train, X_test, y_train, y_test, numpy as np, and confusion_matrix().
"""

# Instructions

"""

    Fit the 1-class SVM and score the test data.
    Compute the observed proportion of outliers in the test data.
    Use np.quantile() to find where to threshold the scores to achieve that proportion.
    Use that threshold to label the test data. Print the confusion matrix.

"""

# solution

# Fit a one-class SVM detector and score the test data
nov_det = onesvm().fit(X_train)
scores = nov_det.score_samples(X_test)

# Find the observed proportion of outliers in the test data
prop = np.mean(y_test==1)

# Compute the appropriate threshold
threshold = np.quantile(scores, prop)

# Print the confusion matrix for the thresholded scores
print(confusion_matrix(y_test, scores > threshold))

#----------------------------------#

# Conclusion

"""
Great, you now have the same amount of control over one-class SVM as you do over other detectors.
"""

[[37 22]
 [17 37]]


'\nGreat, you now have the same amount of control over one-class SVM as you do over other detectors.\n'

In [25]:
data = pd.read_csv(path_data+'hep.csv')
data.head()

features = data.drop('HISTOLOGY', axis=1)
labels = data['HISTOLOGY']

In [29]:
# exercise 06

"""
Find the neighbor

It is clear that the local outlier factor algorithm depends a lot on the idea of a nearest neighbor, which in turn depends on the choice of distance metric. So you decide to experiment some more with the hepatitis dataset introduced in the previous lesson. You are given three examples stored in features, whose classes are stored in labels. You will identify the nearest neighbor to the first example (row with index 0) using three different distance metrics, Euclidean, Hamming and Chebyshev, and on the basis of that choose which distance metric to use. You will import the necessary module as part of the exercise, but pandas and numpy already available, as are features and their labels labels.
"""

# Instructions

"""

    Import the DistanceMetric module as dm.
---

    Compute the pairwise Euclidean, Hamming and Chebyshev distances for all points.
---
Question

Inspect the matrices dist_eucl, dist_hamm and dist_cheb in your terminal and identify the nearest neighbor to the first example for each metric. Noting that the labels of the three examples are, respectively, 2.0, 2.0 and 1.0, pick one of the following answers:
(The Hamming distance works best for this dataset)

"""

# solution

# Import DistanceMetric as dm
from sklearn.metrics import DistanceMetric as dm

# Find the Euclidean distance between all pairs
dist_eucl = dm.get_metric('euclidean').pairwise(features)

# Find the Hamming distance between all pairs
dist_hamm = dm.get_metric('hamming').pairwise(features)

# Find the Chebyshev distance between all pairs
dist_cheb = dm.get_metric('chebyshev').pairwise(features)


display(dist_eucl, dist_hamm, dist_cheb)

#----------------------------------#

# Conclusion

"""
That is right! The Hamming metric correctly sets the first two examples, that both are of class 2.0, to be nearest neigbors.
"""

array([[  0.        ,  20.55042579, 224.91353894, ..., 147.90919512,
         37.059007  ,  35.8036311 ],
       [ 20.55042579,   0.        , 222.11839185, ..., 146.5846172 ,
         41.26899563,  49.80662607],
       [224.91353894, 222.11839185,   0.        , ...,  77.7       ,
        232.09353718, 234.20375744],
       ...,
       [147.90919512, 146.5846172 ,  77.7       , ...,   0.        ,
        155.80789454, 156.95607666],
       [ 37.059007  ,  41.26899563, 232.09353718, ..., 155.80789454,
          0.        ,  22.42966785],
       [ 35.8036311 ,  49.80662607, 234.20375744, ..., 156.95607666,
         22.42966785,   0.        ]])

array([[0.        , 0.52631579, 0.52631579, ..., 0.42105263, 0.63157895,
        0.57894737],
       [0.52631579, 0.        , 0.52631579, ..., 0.52631579, 0.73684211,
        0.78947368],
       [0.52631579, 0.52631579, 0.        , ..., 0.47368421, 0.63157895,
        0.57894737],
       ...,
       [0.42105263, 0.52631579, 0.47368421, ..., 0.        , 0.52631579,
        0.52631579],
       [0.63157895, 0.73684211, 0.63157895, ..., 0.52631579, 0.        ,
        0.52631579],
       [0.57894737, 0.78947368, 0.57894737, ..., 0.52631579, 0.52631579,
        0.        ]])

array([[  0.,  17., 221., ..., 145.,  27.,  33.],
       [ 17.,   0., 219., ..., 143.,  37.,  43.],
       [221., 219.,   0., ...,  76., 230., 230.],
       ...,
       [145., 143.,  76., ...,   0., 154., 154.],
       [ 27.,  37., 230., ..., 154.,   0.,  19.],
       [ 33.,  43., 230., ..., 154.,  19.,   0.]])

'\nThat is right! The Hamming metric correctly sets the first two examples, that both are of class 2.0, to be nearest neigbors.\n'

In [30]:
# exercise 07

"""
Not all metrics agree

In the previous exercise you saw that not all metrics agree when it comes to identifying nearest neighbors. But does this mean they might disagree on outliers, too? You decide to put this to the test. You use the same data as before, but this time feed it into a local outlier factor outlier detector. The module LocalOutlierFactor has been made available to you as lof, and the data is available as features.
"""

# Instructions

"""

    Detect outliers in features using the euclidean metric.
    Detect outliers in features using the hamming metric.
    Detect outliers in features using the jaccard metric.
    Find if all three metrics agree on any one outlier.

"""

# solution

# Compute outliers according to the euclidean metric
out_eucl = lof(metric='euclidean').fit_predict(features)

# Compute outliers according to the hamming metric
out_hamm = lof(metric='hamming').fit_predict(features)

# Compute outliers according to the jaccard metric
out_jacc  = lof(metric='jaccard').fit_predict(features)

# Find if the metrics agree on any one datapoint
print(any(out_eucl + out_hamm + out_jacc == -3))

#----------------------------------#

# Conclusion

"""
There is no datapoint that all three metrics flag as an outlier. So choosing a distance metric should be done with great caution! You now have a concrete understanding of the effect of distance metrics on outlier detection.
"""

False


/home/nero/Documents/Estudos/estudos/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2025: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)


'\nThere is no datapoint that all three metrics flag as an outlier. So choosing a distance metric should be done with great caution! You now have a concrete understanding of the effect of distance metrics on outlier detection.\n'

In [32]:
proteins = pd.read_csv(path_data+'proteins_exercises.csv')

proteins.head()

label                                                seq
0  IMMUNE SYSTEM  LTKCQEEVSHIPAVHPGSFRPKCDENGNYLPLQCYGSIGYCWCVFP...
1  IMMUNE SYSTEM  GPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGV...
2  IMMUNE SYSTEM                 FNMQCQRRFYEALHDPNLNEEQRNAKIKSIRDDC
3  IMMUNE SYSTEM  EVQLVESGGGLVQPGGSLRLSCAASGFTFTDYTMDWVRQAPGKGLE...
4  IMMUNE SYSTEM  DIQMTQSPSSLSASVGDRVTITCKASQDVSIGVAWYQQKPGKAPKL...

In [35]:
%pip install StringDist

  Preparing metadata (setup.py) ... done
  Created wheel for StringDist: filename=StringDist-1.0.9-cp311-cp311-linux_x86_64.whl size=17631 sha256=4b5c398bf79b1378dc9548b88e6c32b9bdde33bf4e872822700aa7442b565304
  Stored in directory: /home/nero/.cache/pip/wheels/fd/d0/9b/188e72fe6cc1ad1ae96a71835adb85cd58b0622a3440b4acdf
Successfully built StringDist
Note: you may need to restart the kernel to use updated packages.


In [40]:
# exercise 08

"""
Restricted Levenshtein

You notice that the stringdist package also implements a variation of Levenshtein distance called the Restricted Damerau-Levenshtein distance, and want to try it out. You will follow the logic from the lesson, wrapping it inside a custom function and precomputing the distance matrix before fitting a local outlier factor anomaly detector. You will measure performance with accuracy_score() which is available to you as accuracy(). You also have access to packages stringdist, numpy as np, pdist() and squareform() from scipy.spatial.distance, and LocalOutlierFactor as lof. The data has been preloaded as a pandas dataframe with two columns, label and sequence, and has two classes: IMMUNE SYSTEM and VIRUS.
"""

# Instructions

"""

    Write a function with input u and v, each of which is an array containing a string, and applies the rdlevenshtein() function on the two strings.
    Reshape the sequence column from proteins by first casting it into an numpy array, and then using .reshape().
    Compute a square distance matrix for sequences using my_rdlevenshtein(), and fit lof on it.
    Compute accuracy by converting preds and proteins['label'] into booleans indicating whether a protein is a virus.

"""

# solution
import stringdist
from scipy.spatial.distance import pdist, squareform
from sklearn.metrics import accuracy_score as accuracy


# Wrap the RD-Levenshtein metric in a custom function
def my_rdlevenshtein(U, v):
    return stringdist.rdlevenshtein(U[0], v[0])

# Reshape the array into a numpy matrix
sequences = np.array(proteins['seq']).reshape(-1, 1)

# Compute the pairwise distance matrix in square form
M = squareform(pdist(sequences, metric=my_rdlevenshtein))

# Run a LoF algorithm on the precomputed distance matrix
preds = lof(metric='precomputed').fit_predict(M)

# Compute the accuracy of the outlier predictions
print(accuracy(proteins['label'] == 'VIRUS', preds==-1))

#----------------------------------#

# Conclusion

"""
Overcoming compatibility problems when working with different Python modules is the sign of a true expert. What's more, you should now feel confident that success is possible even without labels.
"""

/tmp/ipykernel_532341/2410236371.py:28: DeprecationWarning: getargs: The 'u' format is deprecated. Use 'U' instead.
  return stringdist.rdlevenshtein(U[0], v[0])


0.81


"\nOvercoming compatibility problems when working with different Python modules is the sign of a true expert. What's more, you should now feel confident that success is possible even without labels.\n"

In [43]:
# exercise 09

"""
Bringing it all together

In addition to the distance-based learning anomaly detection pipeline you created in the last exercise, you want to also support a feature-based learning one with one-class SVM. You decide to extract two features: first, the length of the string, and, second, a numerical encoding of the first letter of the string, obtained using the function LabelEncoder() described in Chapter 1. To ensure a fair comparison, you will input the outlier scores into an AUC calculation. The following have been imported: LabelEncoder(), roc_auc_score() as auc() and OneClassSVM. The data is available as a pandas data frame called proteins with two columns, label and seq, and two classes, IMMUNE SYSTEM and VIRUS. A fitted LoF detector is available as lof_detector.
"""

# Instructions

"""

    For a string s, len(s) returns its length. Apply that to the seq column to obtain a new column len.
    For a string s, list(s) returns a list of its characters. Use this to extract the first letter of each sequence, and encode it using LabelEncoder().
    LoF scores are in the negative_outlier_factor_ attribute. Compute their AUC.
    Fit a 1-class SVM to a data frame with only len and first as columns. Extract the scores and assess both the LoF scores and the SVM scores using AUC.

"""

# solution
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import roc_auc_score as auc
from sklearn.svm import OneClassSVM

lof_detector = lof(metric='precomputed')
lof_detector.fit(M)


# Create a feature that contains the length of the string
proteins['len'] = proteins['seq'].apply(len)

# Create a feature encoding the first letter of the string
proteins['first'] =  LabelEncoder().fit_transform(proteins['seq'].apply(list).apply(lambda x: x[0]))

# Extract scores from the fitted LoF object, compute its AUC
scores_lof = lof_detector.negative_outlier_factor_
print(auc(proteins['label']=='IMMUNE SYSTEM', scores_lof))

# Fit a 1-class SVM, extract its scores, and compute its AUC
svm = OneClassSVM().fit(proteins[['len', 'first']])
scores_svm = svm.score_samples(proteins[['len', 'first']])
print(auc(proteins['label']=='IMMUNE SYSTEM', scores_svm))

#----------------------------------#

# Conclusion

"""
Congratulations! You have reached the end of this course. You are now ready to take off the kid gloves and face real-world machine learning problems. Good luck!
"""

0.739375
0.6959375


'\nCongratulations! You have reached the end of this course. You are now ready to take off the kid gloves and face real-world machine learning problems. Good luck!\n'