In [5]:
# run this to shorten the data import from the files
path_data = '/home/nero/Documents/Estudos/DataCamp/Python/Introduction_to_TensorFlow_in_Python/datasets/'
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import Variable

In [6]:
borrower_features = Variable([[ 2.,  2., 43.]])

2023-06-21 08:05:16.178340: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-06-21 08:05:16.180111: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1956] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [7]:
# exercise 01

"""
The linear algebra of dense layers

There are two ways to define a dense layer in tensorflow. The first involves the use of low-level, linear algebraic operations. The second makes use of high-level keras operations. In this exercise, we will use the first method to construct the network shown in the image below.

This image depicts an neural network with 5 input nodes and 3 output nodes.

The input layer contains 3 features -- education, marital status, and age -- which are available as borrower_features. The hidden layer contains 2 nodes and the output layer contains a single node.

For each layer, you will take the previous layer as an input, initialize a set of weights, compute the product of the inputs and weights, and then apply an activation function. Note that Variable(), ones(), matmul(), and keras() have been imported from tensorflow.
"""

# Instructions

"""

    Initialize weights1 as a variable using a 3x2 tensor of ones.
    Compute the product of borrower_features by weights1 using matrix multiplication.
    Use a sigmoid activation function to transform product1 + bias1.
---

    Initialize weights2 as a variable using a 2x1 tensor of ones.
    Compute the product of dense1 by weights2 using matrix multiplication.
    Use a sigmoid activation function to transform product2 + bias2.

"""
from tensorflow import Variable, matmul, keras, ones
# solution

# Initialize bias1
bias1 = Variable(1.0)

# Initialize weights1 as 3x2 variable of ones
weights1 = Variable(ones((3, 2)))

# Perform matrix multiplication of borrower_features and weights1
product1 = matmul(borrower_features, weights1)

# Apply sigmoid activation function to product1 + bias1
dense1 = keras.activations.sigmoid(product1 + bias1)

# Print shape of dense1
print("\n dense1's output shape: {}".format(dense1.shape))

#----------------------------------#

# From previous step
bias1 = Variable(1.0)
weights1 = Variable(ones((3, 2)))
product1 = matmul(borrower_features, weights1)
dense1 = keras.activations.sigmoid(product1 + bias1)

# Initialize bias2 and weights2
bias2 = Variable(1.0)
weights2 = Variable(ones((2, 1)))

# Perform matrix multiplication of dense1 and weights2
product2 = matmul(dense1, weights2)

# Apply activation to product2 + bias2 and print the prediction
prediction = keras.activations.sigmoid(product2 + bias2)
print('\n prediction: {}'.format(prediction.numpy()[0,0]))
print('\n actual: 1')

#----------------------------------#

# Conclusion

"""
Excellent work! Our model produces predicted values in the interval between 0 and 1. For the example we considered, the actual value was 1 and the predicted value was a probability between 0 and 1. This, of course, is not meaningful, since we have not yet trained our model's parameters.
"""


 dense1's output shape: (1, 2)

 prediction: 0.9525741338729858

 actual: 1


"\nExcellent work! Our model produces predicted values in the interval between 0 and 1. For the example we considered, the actual value was 1 and the predicted value was a probability between 0 and 1. This, of course, is not meaningful, since we have not yet trained our model's parameters.\n"

In [8]:
data = pd.read_csv(path_data + 'uci_credit_card.csv')
data.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [9]:
columns_borrower = ['EDUCATION','MARRIAGE','AGE']

borrower_features = data.loc[:4, columns_borrower].values
borrower_features = tf.cast(borrower_features, tf.float32)
borrower_features

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 2.,  1., 24.],
       [ 2.,  2., 26.],
       [ 2.,  2., 34.],
       [ 2.,  1., 37.],
       [ 2.,  1., 57.]], dtype=float32)>

In [10]:
# exercise 02

"""
The low-level approach with multiple examples

In this exercise, we'll build further intuition for the low-level approach by constructing the first dense hidden layer for the case where we have multiple examples. We'll assume the model is trained and the first layer weights, weights1, and bias, bias1, are available. We'll then perform matrix multiplication of the borrower_features tensor by the weights1 variable. Recall that the borrower_features tensor includes education, marital status, and age. Finally, we'll apply the sigmoid function to the elements of products1 + bias1, yielding dense1.

Note that matmul() and keras() have been imported from tensorflow.
"""

# Instructions

"""

    Compute products1 by matrix multiplying the features tensor by the weights.
    Use a sigmoid activation function to transform products1 + bias1.
    Print the shapes of borrower_features, weights1, bias1, and dense1.

"""

# solution

# Compute the product of borrower_features and weights1
products1 = matmul(borrower_features, weights1)

# Apply a sigmoid activation function to products1 + bias1
dense1 = keras.activations.sigmoid(products1 + bias1)

# Print the shapes of borrower_features, weights1, bias1, and dense1
print('\n shape of borrower_features: ', borrower_features.shape)
print('\n shape of weights1: ', weights1.shape)
print('\n shape of bias1: ', bias1.shape)
print('\n shape of dense1: ', dense1.shape)

#----------------------------------#

# Conclusion

"""
Good job! Note that our input data, borrower_features, is 5x3 because it consists of 5 examples for 3 features. The shape of weights1 is 3x2, as it was in the previous exercise, since it does not depend on the number of examples. Additionally, bias1 is a scalar. Finally, dense1 is 5x2, which means that we can multiply it by the following set of weights, weights2, which we defined to be 2x1 in the previous exercise.
"""


 shape of borrower_features:  (5, 3)

 shape of weights1:  (3, 2)

 shape of bias1:  ()

 shape of dense1:  (5, 2)


'\nGood job! Note that our input data, borrower_features, is 5x3 because it consists of 5 examples for 3 features. The shape of weights1 is 3x2, as it was in the previous exercise, since it does not depend on the number of examples. Additionally, bias1 is a scalar. Finally, dense1 is 5x2, which means that we can multiply it by the following set of weights, weights2, which we defined to be 2x1 in the previous exercise.\n'

In [11]:
borrower_features = data.loc[:99, columns_borrower].values
borrower_features = tf.cast(borrower_features, tf.float32)
borrower_features[:10]

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[ 2.,  1., 24.],
       [ 2.,  2., 26.],
       [ 2.,  2., 34.],
       [ 2.,  1., 37.],
       [ 2.,  1., 57.],
       [ 1.,  2., 37.],
       [ 1.,  2., 29.],
       [ 2.,  2., 23.],
       [ 3.,  1., 28.],
       [ 3.,  2., 35.]], dtype=float32)>

In [12]:
# exercise 03

"""
Using the dense layer operation

We've now seen how to define dense layers in tensorflow using linear algebra. In this exercise, we'll skip the linear algebra and let keras work out the details. This will allow us to construct the network below, which has 2 hidden layers and 10 features, using less code than we needed for the network with 1 hidden layer and 3 features.

This image depicts an neural network with 10 inputs nodes and 1 output node.

To construct this network, we'll need to define three dense layers, each of which takes the previous layer as an input, multiplies it by weights, and applies an activation function. Note that input data has been defined and is available as a 100x10 tensor: borrower_features. Additionally, the keras.layers module is available.
"""

# Instructions

"""

    Set dense1 to be a dense layer with 7 output nodes and a sigmoid activation function.
    Define dense2 to be dense layer with 3 output nodes and a sigmoid activation function.
    Define predictions to be a dense layer with 1 output node and a sigmoid activation function.
    Print the shapes of dense1, dense2, and predictions in that order using the .shape method. Why does each of these tensors have 100 rows?

"""

# solution

# Define the first dense layer
dense1 = keras.layers.Dense(7, activation='sigmoid')(borrower_features)

# Define a dense layer with 3 output nodes
dense2 = keras.layers.Dense(3, activation='sigmoid')(dense1)

# Define a dense layer with 1 output node
predictions = keras.layers.Dense(1, activation='sigmoid')(dense2)

# Print the shapes of dense1, dense2, and predictions
print('\n shape of dense1: ', dense1.shape)
print('\n shape of dense2: ', dense2.shape)
print('\n shape of predictions: ', predictions.shape)

#----------------------------------#

# Conclusion

"""
Great work! With just 8 lines of code, you were able to define 2 dense hidden layers and an output layer. This is the advantage of using high-level operations in tensorflow. Note that each layer has 100 rows because the input data contains 100 examples.
"""


 shape of dense1:  (100, 7)

 shape of dense2:  (100, 3)

 shape of predictions:  (100, 1)


'\nGreat work! With just 8 lines of code, you were able to define 2 dense hidden layers and an output layer. This is the advantage of using high-level operations in tensorflow. Note that each layer has 100 rows because the input data contains 100 examples.\n'

In [14]:
bill_columns = ['PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']

bill_amounts = data.loc[:,bill_columns].values

default = data['default.payment.next.month'].values

In [15]:
# exercise 04

"""
Binary classification problems

In this exercise, you will again make use of credit card data. The target variable, default, indicates whether a credit card holder defaults on his or her payment in the following period. Since there are only two options--default or not--this is a binary classification problem. While the dataset has many features, you will focus on just three: the size of the three latest credit card bills. Finally, you will compute predictions from your untrained network, outputs, and compare those the target variable, default.

The tensor of features has been loaded and is available as bill_amounts. Additionally, the constant(), float32, and keras.layers.Dense() operations are available.
"""

# Instructions

"""

    Define inputs as a 32-bit floating point constant tensor using bill_amounts.
    Set dense1 to be a dense layer with 3 output nodes and a relu activation function.
    Set dense2 to be a dense layer with 2 output nodes and a relu activation function.
    Set the output layer to be a dense layer with a single output node and a sigmoid activation function.

"""

# solution
from tensorflow import constant, float32
# Construct input layer from features
inputs = constant(bill_amounts, float32)

# Define first dense layer
dense1 = keras.layers.Dense(3, activation='relu')(inputs)

# Define second dense layer
dense2 = keras.layers.Dense(2, activation='relu')(dense1)

# Define output layer
outputs = keras.layers.Dense(1, activation='sigmoid')(dense2)

# Print error for first five examples
error = default[:5] - outputs.numpy()[:5]
print(error)

#----------------------------------#

# Conclusion

"""
Excellent work! If you run the code several times, you'll notice that the errors change each time. This is because you're using an untrained model with randomly initialized parameters. Furthermore, the errors fall on the interval between -1 and 1 because default is a binary variable that takes on values of 0 and 1 and outputs is a probability between 0 and 1.
"""

[[ 0.5  0.5 -0.5 -0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5 -0.5]
 [ 1.   1.   0.   0.   0. ]
 [ 0.5  0.5 -0.5 -0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5 -0.5]]


"\nExcellent work! If you run the code several times, you'll notice that the errors change each time. This is because you're using an untrained model with randomly initialized parameters. Furthermore, the errors fall on the interval between -1 and 1 because default is a binary variable that takes on values of 0 and 1 and outputs is a probability between 0 and 1.\n"

In [16]:
data.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [17]:
borrower_features = data.iloc[:, [1,2,4,5,6,7,8,9,10]].values
borrower_features

array([[ 2.0e+04,  2.0e+00,  1.0e+00, ..., -1.0e+00, -1.0e+00, -2.0e+00],
       [ 1.2e+05,  2.0e+00,  2.0e+00, ...,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 9.0e+04,  2.0e+00,  2.0e+00, ...,  0.0e+00,  0.0e+00,  0.0e+00],
       ...,
       [ 3.0e+04,  1.0e+00,  2.0e+00, ...,  2.0e+00, -1.0e+00,  0.0e+00],
       [ 8.0e+04,  1.0e+00,  1.0e+00, ...,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 5.0e+04,  1.0e+00,  1.0e+00, ...,  0.0e+00,  0.0e+00,  0.0e+00]])

In [18]:
# exercise 05

"""
Multiclass classification problems

In this exercise, we expand beyond binary classification to cover multiclass problems. A multiclass problem has targets that can take on three or more values. In the credit card dataset, the education variable can take on 6 different values, each corresponding to a different level of education. We will use that as our target in this exercise and will also expand the feature set from 3 to 10 columns.

As in the previous problem, you will define an input layer, dense layers, and an output layer. You will also print the untrained model's predictions, which are probabilities assigned to the classes. The tensor of features has been loaded and is available as borrower_features. Additionally, the constant(), float32, and keras.layers.Dense() operations are available.
"""

# Instructions

"""

    Define the input layer as a 32-bit constant tensor using borrower_features.
    Set the first dense layer to have 10 output nodes and a sigmoid activation function.
    Set the second dense layer to have 8 output nodes and a rectified linear unit activation function.
    Set the output layer to have 6 output nodes and the appropriate activation function.

"""

# solution

# Construct input layer from borrower features
inputs = constant(borrower_features, float32)

# Define first dense layer
dense1 = keras.layers.Dense(10, activation='sigmoid')(inputs)

# Define second dense layer
dense2 = keras.layers.Dense(8, activation='relu')(dense1)

# Define output layer
outputs = keras.layers.Dense(6, activation='softmax')(dense2)

# Print first five predictions
print(outputs.numpy()[:5])

#----------------------------------#

# Conclusion
print(
"""
Great work! Notice that each row of outputs sums to one. This is because a row contains the predicted class probabilities for one example. As with the previous exercise, our predictions are not yet informative, since we are using an untrained model with randomly initialized parameters. This is why the model tends to assign similar probabilities to each class.
""")

[[0.1968281  0.13855846 0.20595923 0.19947822 0.12251294 0.13666312]
 [0.1968281  0.13855846 0.20595923 0.19947822 0.12251294 0.13666312]
 [0.1968281  0.13855846 0.20595923 0.19947822 0.12251294 0.13666312]
 [0.1968281  0.13855846 0.20595923 0.19947822 0.12251294 0.13666312]
 [0.1968281  0.13855846 0.20595923 0.19947822 0.12251294 0.13666312]]

Great work! Notice that each row of outputs sums to one. This is because a row contains the predicted class probabilities for one example. As with the previous exercise, our predictions are not yet informative, since we are using an untrained model with randomly initialized parameters. This is why the model tends to assign similar probabilities to each class.



In [19]:
import math
from tensorflow import divide

pi = math.pi
def loss_function(x):
	return 4.0*math.cos(x-1)+divide(math.cos(2.0*pi*x),x)

In [20]:
# exercise 06

"""
The dangers of local minima

Consider the plot of the following loss function, loss_function(), which contains a global minimum, marked by the dot on the right, and several local minima, including the one marked by the dot on the left.

The graph is of a single variable function that contains multiple local minima and a global minimum.

In this exercise, you will try to find the global minimum of loss_function() using keras.optimizers.SGD(). You will do this twice, each time with a different initial value of the input to loss_function(). First, you will use x_1, which is a variable with an initial value of 6.0. Second, you will use x_2, which is a variable with an initial value of 0.3. Note that loss_function() has been defined and is available.
"""

# Instructions

"""

    Set opt to use the stochastic gradient descent optimizer (SGD) with a learning rate of 0.01.
    Perform minimization using the loss function, loss_function(), and the variable with an initial value of 6.0, x_1.
    Perform minimization using the loss function, loss_function(), and the variable with an initial value of 0.3, x_2.
    Print x_1 and x_2 as numpy arrays and check whether the values differ. These are the minima that the algorithm identified.

"""

# solution

# Initialize x_1 and x_2
x_1 = Variable(6.0,float32)
x_2 = Variable(0.3,float32)

# Define the optimization operation
opt = keras.optimizers.legacy.SGD(learning_rate=0.01)

for j in range(100):
	# Perform minimization using the loss function and x_1
	opt.minimize(lambda: loss_function(x_1), var_list=[x_1])
	# Perform minimization using the loss function and x_2
	opt.minimize(lambda: loss_function(x_2), var_list=[x_2])

# Print x_1 and x_2 as numpy arrays
print(x_1.numpy(), x_2.numpy())

#----------------------------------#

# Conclusion

"""
Great work! Notice that we used the same optimizer and loss function, but two different initial values. When we started at 6.0 with x_1, we found the global minimum at 4.38, marked by the dot on the right. When we started at 0.3, we stopped around 0.42 with x_2, the local minimum marked by a dot on the far left.
"""

6.027515 0.25


'\nGreat work! Notice that we used the same optimizer and loss function, but two different initial values. When we started at 6.0 with x_1, we found the global minimum at 4.38, marked by the dot on the right. When we started at 0.3, we stopped around 0.42 with x_2, the local minimum marked by a dot on the far left.\n'

In [21]:
# exercise 07

"""
Avoiding local minima

The previous problem showed how easy it is to get stuck in local minima. We had a simple optimization problem in one variable and gradient descent still failed to deliver the global minimum when we had to travel through local minima first. One way to avoid this problem is to use momentum, which allows the optimizer to break through local minima. We will again use the loss function from the previous problem, which has been defined and is available for you as loss_function().

The graph is of a single variable function that contains multiple local minima and a global minimum.

Several optimizers in tensorflow have a momentum parameter, including SGD and RMSprop. You will make use of RMSprop in this exercise. Note that x_1 and x_2 have been initialized to the same value this time. Furthermore, keras.optimizers.RMSprop() has also been imported for you from tensorflow.
"""

# Instructions

"""

    Set the opt_1 operation to use a learning rate of 0.01 and a momentum of 0.99.
    Set opt_2 to use the root mean square propagation (RMS) optimizer with a learning rate of 0.01 and a momentum of 0.00.
    Define the minimization operation for opt_2.
    Print x_1 and x_2 as numpy arrays.

"""

# solution

# Initialize x_1 and x_2
x_1 = Variable(0.05,float32)
x_2 = Variable(0.05,float32)

# Define the optimization operation for opt_1 and opt_2
opt_1 = keras.optimizers.RMSprop(learning_rate=0.01, momentum=0.99)
opt_2 = keras.optimizers.RMSprop(learning_rate=0.01, momentum=0.00)

for j in range(100):
	opt_1.minimize(lambda: loss_function(x_1), var_list=[x_1])
    # Define the minimization operation for opt_2
	opt_2.minimize(lambda: loss_function(x_2), var_list=[x_2])

# Print x_1 and x_2 as numpy arrays
print(x_1.numpy(), x_2.numpy())

#----------------------------------#

# Conclusion

"""
Good work! Recall that the global minimum is approximately 4.38. Notice that opt_1 built momentum, bringing x_1 closer to the global minimum. To the contrary, opt_2, which had a momentum parameter of 0.0, got stuck in the local minimum on the left.
"""

2.744512 0.24999999


'\nGood work! Recall that the global minimum is approximately 4.38. Notice that opt_1 built momentum, bringing x_1 closer to the global minimum. To the contrary, opt_2, which had a momentum parameter of 0.0, got stuck in the local minimum on the left.\n'

In [22]:
# exercise 08

"""
Initialization in TensorFlow

A good initialization can reduce the amount of time needed to find the global minimum. In this exercise, we will initialize weights and biases for a neural network that will be used to predict credit card default decisions. To build intuition, we will use the low-level, linear algebraic approach, rather than making use of convenience functions and high-level keras operations. We will also expand the set of input features from 3 to 23. Several operations have been imported from tensorflow: Variable(), random(), and ones().
"""

# Instructions

"""

    Initialize the layer 1 weights, w1, as a Variable() with shape [23, 7], drawn from a normal distribution.
    Initialize the layer 1 bias using ones.
    Use a draw from the normal distribution to initialize w2 as a Variable() with shape [7, 1].
    Define b2 as a Variable() and set its initial value to 0.0.

"""
from tensorflow import  random
# solution

# Define the layer 1 weights
w1 = Variable(random.normal([23, 7]))

# Initialize the layer 1 bias
b1 = Variable(ones([7]))

# Define the layer 2 weights
w2 = Variable(random.normal([7,1]))

# Define the layer 2 bias
b2 = Variable(0.0)

#----------------------------------#

# Conclusion

"""
Excellent work! In the next exercise, you will start where we've ended and will finish constructing the neural network.
"""

"\nExcellent work! In the next exercise, you will start where we've ended and will finish constructing the neural network.\n"

In [32]:
# exercise 09

"""
Defining the model and loss function

In this exercise, you will train a neural network to predict whether a credit card holder will default. The features and targets you will use to train your network are available in the Python shell as borrower_features and default. You defined the weights and biases in the previous exercise.

Note that the predictions layer is defined as
, where

is the sigmoid activation, layer1 is a tensor of nodes for the first hidden dense layer, w2 is a tensor of weights, and b2 is the bias tensor.

The trainable variables are w1, b1, w2, and b2. Additionally, the following operations have been imported for you: keras.activations.relu() and keras.layers.Dropout().
"""

# Instructions

"""

    Apply a rectified linear unit activation function to the first layer.
    Apply 25% dropout to layer1.
    Pass the target, targets, and the predicted values, predictions, to the cross entropy loss function.

"""

# solution

# Define the model
def model(w1, b1, w2, b2, features = borrower_features):
	# Apply relu activation functions to layer 1
	layer1 = keras.activations.relu(matmul(features, w1) + b1)
    # Apply dropout rate of 0.25
	dropout = keras.layers.Dropout(0.25)(layer1)
	return keras.activations.sigmoid(matmul(dropout, w2) + b2)

# Define the loss function
def loss_function(w1, b1, w2, b2, features = borrower_features, targets = default):
	predictions = model(w1, b1, w2, b2)
	# Pass targets and predictions to the cross entropy loss
	return keras.losses.binary_crossentropy(targets, predictions)

#----------------------------------#

# Conclusion

"""
Nice work! One of the benefits of using tensorflow is that you have the option to customize models down to the linear algebraic-level, as we've shown in the last two exercises. If you print w1, you can see that the objects we're working with are simply tensors.
"""

"\nNice work! One of the benefits of using tensorflow is that you have the option to customize models down to the linear algebraic-level, as we've shown in the last two exercises. If you print w1, you can see that the objects we're working with are simply tensors.\n"

In [24]:
data.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [25]:
import matplotlib.pyplot as plt
from pandas import crosstab
from seaborn import heatmap

def confusion_matrix(default, model_predictions):
	df = DataFrame(np.hstack([default, model_predictions.numpy() > 0.5]), columns = ['Actual','Predicted'])
	confusion_matrix = crosstab(df['Actual'], df['Predicted'], rownames=['Actual'], colnames=['Predicted'])
	heatmap(confusion_matrix, cmap="Greys", fmt="d", annot=True, cbar=False)
	plt.show()

In [26]:
from sklearn.model_selection import train_test_split as tts

X = data.drop(columns=['ID','default.payment.next.month']).values
y = data['default.payment.next.month'].values

X_train, X_test, y_train, y_test = tts(X,y, test_size = 0.3)

In [35]:
test_features = tf.Variable(X_test, float32)

test_features = tf.cast(test_features, float32)

In [ ]:
layer1 = keras.activations.relu(tf.matmul(tf.cast(features, tf.float64), tf.cast(w1, tf.float64)) + b1)


In [ ]:
# exercise 10

"""
Training neural networks with TensorFlow

In the previous exercise, you defined a model, model(w1, b1, w2, b2, features), and a loss function, loss_function(w1, b1, w2, b2, features, targets), both of which are available to you in this exercise. You will now train the model and then evaluate its performance by predicting default outcomes in a test set, which consists of test_features and test_targets and is available to you. The trainable variables are w1, b1, w2, and b2. Additionally, the following operations have been imported for you: keras.activations.relu() and keras.layers.Dropout().
"""

# Instructions

"""

    Set the optimizer to perform minimization.
    Add the four trainable variables to var_list in the order in which they appear as arguments to loss_function().
    Use the model and test_features to predict the values for test_targets.

"""

# solution

# Train the model
for j in range(100):
    # Complete the optimizer
	opt.minimize(lambda: loss_function(w1, b1, w2, b2), 
                 var_list=[w1, b1, w2, b2])

# Make predictions with model using test features
model_predictions = model(w1, b1, w2, b2, test_features)

# Construct the confusion matrix
confusion_matrix(test_targets, model_predictions)

#----------------------------------#

# Conclusion

"""
Nice work! The diagram shown is called a ``confusion matrix.'' The diagonal elements show the number of correct predictions. The off-diagonal elements show the number of incorrect predictions. We can see that the model performs reasonably-well, but does so by overpredicting non-default. This suggests that we may need to train longer, tune the model's hyperparameters, or change the model's architecture.
"""